/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.portfolio.Bio', null, global);
goog.exportSymbol('proto.portfolio.Course', null, global);
goog.exportSymbol('proto.portfolio.Education', null, global);
goog.exportSymbol('proto.portfolio.Experience', null, global);
goog.exportSymbol('proto.portfolio.GetBioRequest', null, global);
goog.exportSymbol('proto.portfolio.GetBioResponse', null, global);
goog.exportSymbol('proto.portfolio.GetCVRequest', null, global);
goog.exportSymbol('proto.portfolio.GetCVResponse', null, global);
goog.exportSymbol('proto.portfolio.Job', null, global);
goog.exportSymbol('proto.portfolio.ListProjectsRequest', null, global);
goog.exportSymbol('proto.portfolio.ListProjectsResponse', null, global);
goog.exportSymbol('proto.portfolio.Project', null, global);
goog.exportSymbol('proto.portfolio.Projects', null, global);
goog.exportSymbol('proto.portfolio.Skill', null, global);
goog.exportSymbol('proto.portfolio.Skills', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.portfolio.Bio = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.portfolio.Bio, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.portfolio.Bio.displayName = 'proto.portfolio.Bio';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.portfolio.Bio.prototype.toObject = function(opt_includeInstance) {
  return proto.portfolio.Bio.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.portfolio.Bio} msg The msg instance to transform.
 * @return {!Object}
 */
proto.portfolio.Bio.toObject = function(includeInstance, msg) {
  var f, obj = {
    title: msg.getTitle(),
    description: msg.getDescription()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.portfolio.Bio}
 */
proto.portfolio.Bio.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.portfolio.Bio;
  return proto.portfolio.Bio.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.portfolio.Bio} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.portfolio.Bio}
 */
proto.portfolio.Bio.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setTitle(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.portfolio.Bio} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.portfolio.Bio.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.portfolio.Bio.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.portfolio.Bio.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getTitle();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = this.getDescription();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.portfolio.Bio} The clone.
 */
proto.portfolio.Bio.prototype.cloneMessage = function() {
  return /** @type {!proto.portfolio.Bio} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional string title = 1;
 * @return {string}
 */
proto.portfolio.Bio.prototype.getTitle = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 1, ""));
};


/** @param {string} value  */
proto.portfolio.Bio.prototype.setTitle = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional string description = 2;
 * @return {string}
 */
proto.portfolio.Bio.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 2, ""));
};


/** @param {string} value  */
proto.portfolio.Bio.prototype.setDescription = function(value) {
  jspb.Message.setField(this, 2, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.portfolio.Course = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.portfolio.Course, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.portfolio.Course.displayName = 'proto.portfolio.Course';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.portfolio.Course.prototype.toObject = function(opt_includeInstance) {
  return proto.portfolio.Course.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.portfolio.Course} msg The msg instance to transform.
 * @return {!Object}
 */
proto.portfolio.Course.toObject = function(includeInstance, msg) {
  var f, obj = {
    institution: msg.getInstitution(),
    description: msg.getDescription(),
    dates: msg.getDates(),
    name: msg.getName()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.portfolio.Course}
 */
proto.portfolio.Course.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.portfolio.Course;
  return proto.portfolio.Course.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.portfolio.Course} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.portfolio.Course}
 */
proto.portfolio.Course.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setInstitution(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setDates(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.portfolio.Course} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.portfolio.Course.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.portfolio.Course.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.portfolio.Course.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getInstitution();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = this.getDescription();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = this.getDates();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = this.getName();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
};


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.portfolio.Course} The clone.
 */
proto.portfolio.Course.prototype.cloneMessage = function() {
  return /** @type {!proto.portfolio.Course} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional string institution = 1;
 * @return {string}
 */
proto.portfolio.Course.prototype.getInstitution = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 1, ""));
};


/** @param {string} value  */
proto.portfolio.Course.prototype.setInstitution = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional string description = 2;
 * @return {string}
 */
proto.portfolio.Course.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 2, ""));
};


/** @param {string} value  */
proto.portfolio.Course.prototype.setDescription = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional string dates = 3;
 * @return {string}
 */
proto.portfolio.Course.prototype.getDates = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 3, ""));
};


/** @param {string} value  */
proto.portfolio.Course.prototype.setDates = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * optional string name = 4;
 * @return {string}
 */
proto.portfolio.Course.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 4, ""));
};


/** @param {string} value  */
proto.portfolio.Course.prototype.setName = function(value) {
  jspb.Message.setField(this, 4, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.portfolio.Education = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.portfolio.Education.repeatedFields_, null);
};
goog.inherits(proto.portfolio.Education, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.portfolio.Education.displayName = 'proto.portfolio.Education';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.portfolio.Education.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.portfolio.Education.prototype.toObject = function(opt_includeInstance) {
  return proto.portfolio.Education.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.portfolio.Education} msg The msg instance to transform.
 * @return {!Object}
 */
proto.portfolio.Education.toObject = function(includeInstance, msg) {
  var f, obj = {
    coursesList: jspb.Message.toObjectList(msg.getCoursesList(),
    proto.portfolio.Course.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.portfolio.Education}
 */
proto.portfolio.Education.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.portfolio.Education;
  return proto.portfolio.Education.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.portfolio.Education} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.portfolio.Education}
 */
proto.portfolio.Education.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.portfolio.Course;
      reader.readMessage(value,proto.portfolio.Course.deserializeBinaryFromReader);
      msg.getCoursesList().push(value);
      msg.setCoursesList(msg.getCoursesList());
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.portfolio.Education} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.portfolio.Education.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.portfolio.Education.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.portfolio.Education.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getCoursesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.portfolio.Course.serializeBinaryToWriter
    );
  }
};


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.portfolio.Education} The clone.
 */
proto.portfolio.Education.prototype.cloneMessage = function() {
  return /** @type {!proto.portfolio.Education} */ (jspb.Message.cloneMessage(this));
};


/**
 * repeated Course courses = 1;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.portfolio.Course>}
 */
proto.portfolio.Education.prototype.getCoursesList = function() {
  return /** @type{!Array.<!proto.portfolio.Course>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.portfolio.Course, 1));
};


/** @param {Array.<!proto.portfolio.Course>} value  */
proto.portfolio.Education.prototype.setCoursesList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


proto.portfolio.Education.prototype.clearCoursesList = function() {
  this.setCoursesList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.portfolio.Skill = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.portfolio.Skill, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.portfolio.Skill.displayName = 'proto.portfolio.Skill';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.portfolio.Skill.prototype.toObject = function(opt_includeInstance) {
  return proto.portfolio.Skill.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.portfolio.Skill} msg The msg instance to transform.
 * @return {!Object}
 */
proto.portfolio.Skill.toObject = function(includeInstance, msg) {
  var f, obj = {
    category: msg.getCategory(),
    type: msg.getType(),
    description: msg.getDescription()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.portfolio.Skill}
 */
proto.portfolio.Skill.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.portfolio.Skill;
  return proto.portfolio.Skill.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.portfolio.Skill} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.portfolio.Skill}
 */
proto.portfolio.Skill.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setCategory(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setType(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.portfolio.Skill} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.portfolio.Skill.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.portfolio.Skill.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.portfolio.Skill.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getCategory();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = this.getType();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = this.getDescription();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.portfolio.Skill} The clone.
 */
proto.portfolio.Skill.prototype.cloneMessage = function() {
  return /** @type {!proto.portfolio.Skill} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional string category = 1;
 * @return {string}
 */
proto.portfolio.Skill.prototype.getCategory = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 1, ""));
};


/** @param {string} value  */
proto.portfolio.Skill.prototype.setCategory = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional string type = 2;
 * @return {string}
 */
proto.portfolio.Skill.prototype.getType = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 2, ""));
};


/** @param {string} value  */
proto.portfolio.Skill.prototype.setType = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional string description = 3;
 * @return {string}
 */
proto.portfolio.Skill.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 3, ""));
};


/** @param {string} value  */
proto.portfolio.Skill.prototype.setDescription = function(value) {
  jspb.Message.setField(this, 3, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.portfolio.Skills = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.portfolio.Skills.repeatedFields_, null);
};
goog.inherits(proto.portfolio.Skills, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.portfolio.Skills.displayName = 'proto.portfolio.Skills';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.portfolio.Skills.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.portfolio.Skills.prototype.toObject = function(opt_includeInstance) {
  return proto.portfolio.Skills.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.portfolio.Skills} msg The msg instance to transform.
 * @return {!Object}
 */
proto.portfolio.Skills.toObject = function(includeInstance, msg) {
  var f, obj = {
    skillsList: jspb.Message.toObjectList(msg.getSkillsList(),
    proto.portfolio.Skill.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.portfolio.Skills}
 */
proto.portfolio.Skills.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.portfolio.Skills;
  return proto.portfolio.Skills.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.portfolio.Skills} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.portfolio.Skills}
 */
proto.portfolio.Skills.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.portfolio.Skill;
      reader.readMessage(value,proto.portfolio.Skill.deserializeBinaryFromReader);
      msg.getSkillsList().push(value);
      msg.setSkillsList(msg.getSkillsList());
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.portfolio.Skills} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.portfolio.Skills.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.portfolio.Skills.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.portfolio.Skills.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getSkillsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.portfolio.Skill.serializeBinaryToWriter
    );
  }
};


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.portfolio.Skills} The clone.
 */
proto.portfolio.Skills.prototype.cloneMessage = function() {
  return /** @type {!proto.portfolio.Skills} */ (jspb.Message.cloneMessage(this));
};


/**
 * repeated Skill skills = 1;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.portfolio.Skill>}
 */
proto.portfolio.Skills.prototype.getSkillsList = function() {
  return /** @type{!Array.<!proto.portfolio.Skill>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.portfolio.Skill, 1));
};


/** @param {Array.<!proto.portfolio.Skill>} value  */
proto.portfolio.Skills.prototype.setSkillsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


proto.portfolio.Skills.prototype.clearSkillsList = function() {
  this.setSkillsList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.portfolio.Project = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.portfolio.Project, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.portfolio.Project.displayName = 'proto.portfolio.Project';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.portfolio.Project.prototype.toObject = function(opt_includeInstance) {
  return proto.portfolio.Project.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.portfolio.Project} msg The msg instance to transform.
 * @return {!Object}
 */
proto.portfolio.Project.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: msg.getId(),
    title: msg.getTitle(),
    meta: msg.getMeta(),
    description: msg.getDescription()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.portfolio.Project}
 */
proto.portfolio.Project.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.portfolio.Project;
  return proto.portfolio.Project.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.portfolio.Project} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.portfolio.Project}
 */
proto.portfolio.Project.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setTitle(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setMeta(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.portfolio.Project} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.portfolio.Project.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.portfolio.Project.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.portfolio.Project.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getId();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = this.getTitle();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = this.getMeta();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = this.getDescription();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
};


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.portfolio.Project} The clone.
 */
proto.portfolio.Project.prototype.cloneMessage = function() {
  return /** @type {!proto.portfolio.Project} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional int32 id = 1;
 * @return {number}
 */
proto.portfolio.Project.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 1, 0));
};


/** @param {number} value  */
proto.portfolio.Project.prototype.setId = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional string title = 2;
 * @return {string}
 */
proto.portfolio.Project.prototype.getTitle = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 2, ""));
};


/** @param {string} value  */
proto.portfolio.Project.prototype.setTitle = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional string meta = 3;
 * @return {string}
 */
proto.portfolio.Project.prototype.getMeta = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 3, ""));
};


/** @param {string} value  */
proto.portfolio.Project.prototype.setMeta = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * optional string description = 4;
 * @return {string}
 */
proto.portfolio.Project.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 4, ""));
};


/** @param {string} value  */
proto.portfolio.Project.prototype.setDescription = function(value) {
  jspb.Message.setField(this, 4, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.portfolio.Projects = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.portfolio.Projects.repeatedFields_, null);
};
goog.inherits(proto.portfolio.Projects, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.portfolio.Projects.displayName = 'proto.portfolio.Projects';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.portfolio.Projects.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.portfolio.Projects.prototype.toObject = function(opt_includeInstance) {
  return proto.portfolio.Projects.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.portfolio.Projects} msg The msg instance to transform.
 * @return {!Object}
 */
proto.portfolio.Projects.toObject = function(includeInstance, msg) {
  var f, obj = {
    projectsList: jspb.Message.toObjectList(msg.getProjectsList(),
    proto.portfolio.Project.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.portfolio.Projects}
 */
proto.portfolio.Projects.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.portfolio.Projects;
  return proto.portfolio.Projects.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.portfolio.Projects} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.portfolio.Projects}
 */
proto.portfolio.Projects.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.portfolio.Project;
      reader.readMessage(value,proto.portfolio.Project.deserializeBinaryFromReader);
      msg.getProjectsList().push(value);
      msg.setProjectsList(msg.getProjectsList());
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.portfolio.Projects} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.portfolio.Projects.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.portfolio.Projects.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.portfolio.Projects.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getProjectsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.portfolio.Project.serializeBinaryToWriter
    );
  }
};


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.portfolio.Projects} The clone.
 */
proto.portfolio.Projects.prototype.cloneMessage = function() {
  return /** @type {!proto.portfolio.Projects} */ (jspb.Message.cloneMessage(this));
};


/**
 * repeated Project projects = 1;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.portfolio.Project>}
 */
proto.portfolio.Projects.prototype.getProjectsList = function() {
  return /** @type{!Array.<!proto.portfolio.Project>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.portfolio.Project, 1));
};


/** @param {Array.<!proto.portfolio.Project>} value  */
proto.portfolio.Projects.prototype.setProjectsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


proto.portfolio.Projects.prototype.clearProjectsList = function() {
  this.setProjectsList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.portfolio.Job = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.portfolio.Job, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.portfolio.Job.displayName = 'proto.portfolio.Job';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.portfolio.Job.prototype.toObject = function(opt_includeInstance) {
  return proto.portfolio.Job.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.portfolio.Job} msg The msg instance to transform.
 * @return {!Object}
 */
proto.portfolio.Job.toObject = function(includeInstance, msg) {
  var f, obj = {
    company: msg.getCompany(),
    jobTitle: msg.getJobTitle(),
    location: msg.getLocation(),
    dates: msg.getDates(),
    description: msg.getDescription(),
    logoUrl: msg.getLogoUrl()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.portfolio.Job}
 */
proto.portfolio.Job.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.portfolio.Job;
  return proto.portfolio.Job.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.portfolio.Job} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.portfolio.Job}
 */
proto.portfolio.Job.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setCompany(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setJobTitle(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setLocation(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setDates(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setLogoUrl(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.portfolio.Job} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.portfolio.Job.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.portfolio.Job.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.portfolio.Job.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getCompany();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = this.getJobTitle();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = this.getLocation();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = this.getDates();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = this.getDescription();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = this.getLogoUrl();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
};


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.portfolio.Job} The clone.
 */
proto.portfolio.Job.prototype.cloneMessage = function() {
  return /** @type {!proto.portfolio.Job} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional string company = 1;
 * @return {string}
 */
proto.portfolio.Job.prototype.getCompany = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 1, ""));
};


/** @param {string} value  */
proto.portfolio.Job.prototype.setCompany = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional string job_title = 2;
 * @return {string}
 */
proto.portfolio.Job.prototype.getJobTitle = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 2, ""));
};


/** @param {string} value  */
proto.portfolio.Job.prototype.setJobTitle = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional string location = 3;
 * @return {string}
 */
proto.portfolio.Job.prototype.getLocation = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 3, ""));
};


/** @param {string} value  */
proto.portfolio.Job.prototype.setLocation = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * optional string dates = 4;
 * @return {string}
 */
proto.portfolio.Job.prototype.getDates = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 4, ""));
};


/** @param {string} value  */
proto.portfolio.Job.prototype.setDates = function(value) {
  jspb.Message.setField(this, 4, value);
};


/**
 * optional string description = 5;
 * @return {string}
 */
proto.portfolio.Job.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 5, ""));
};


/** @param {string} value  */
proto.portfolio.Job.prototype.setDescription = function(value) {
  jspb.Message.setField(this, 5, value);
};


/**
 * optional string logo_url = 6;
 * @return {string}
 */
proto.portfolio.Job.prototype.getLogoUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 6, ""));
};


/** @param {string} value  */
proto.portfolio.Job.prototype.setLogoUrl = function(value) {
  jspb.Message.setField(this, 6, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.portfolio.Experience = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.portfolio.Experience.repeatedFields_, null);
};
goog.inherits(proto.portfolio.Experience, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.portfolio.Experience.displayName = 'proto.portfolio.Experience';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.portfolio.Experience.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.portfolio.Experience.prototype.toObject = function(opt_includeInstance) {
  return proto.portfolio.Experience.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.portfolio.Experience} msg The msg instance to transform.
 * @return {!Object}
 */
proto.portfolio.Experience.toObject = function(includeInstance, msg) {
  var f, obj = {
    jobsList: jspb.Message.toObjectList(msg.getJobsList(),
    proto.portfolio.Job.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.portfolio.Experience}
 */
proto.portfolio.Experience.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.portfolio.Experience;
  return proto.portfolio.Experience.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.portfolio.Experience} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.portfolio.Experience}
 */
proto.portfolio.Experience.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.portfolio.Job;
      reader.readMessage(value,proto.portfolio.Job.deserializeBinaryFromReader);
      msg.getJobsList().push(value);
      msg.setJobsList(msg.getJobsList());
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.portfolio.Experience} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.portfolio.Experience.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.portfolio.Experience.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.portfolio.Experience.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getJobsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.portfolio.Job.serializeBinaryToWriter
    );
  }
};


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.portfolio.Experience} The clone.
 */
proto.portfolio.Experience.prototype.cloneMessage = function() {
  return /** @type {!proto.portfolio.Experience} */ (jspb.Message.cloneMessage(this));
};


/**
 * repeated Job jobs = 1;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.portfolio.Job>}
 */
proto.portfolio.Experience.prototype.getJobsList = function() {
  return /** @type{!Array.<!proto.portfolio.Job>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.portfolio.Job, 1));
};


/** @param {Array.<!proto.portfolio.Job>} value  */
proto.portfolio.Experience.prototype.setJobsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


proto.portfolio.Experience.prototype.clearJobsList = function() {
  this.setJobsList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.portfolio.GetBioResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.portfolio.GetBioResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.portfolio.GetBioResponse.displayName = 'proto.portfolio.GetBioResponse';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.portfolio.GetBioResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.portfolio.GetBioResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.portfolio.GetBioResponse} msg The msg instance to transform.
 * @return {!Object}
 */
proto.portfolio.GetBioResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    bio: (f = msg.getBio()) && proto.portfolio.Bio.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.portfolio.GetBioResponse}
 */
proto.portfolio.GetBioResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.portfolio.GetBioResponse;
  return proto.portfolio.GetBioResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.portfolio.GetBioResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.portfolio.GetBioResponse}
 */
proto.portfolio.GetBioResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.portfolio.Bio;
      reader.readMessage(value,proto.portfolio.Bio.deserializeBinaryFromReader);
      msg.setBio(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.portfolio.GetBioResponse} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.portfolio.GetBioResponse.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.portfolio.GetBioResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.portfolio.GetBioResponse.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getBio();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.portfolio.Bio.serializeBinaryToWriter
    );
  }
};


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.portfolio.GetBioResponse} The clone.
 */
proto.portfolio.GetBioResponse.prototype.cloneMessage = function() {
  return /** @type {!proto.portfolio.GetBioResponse} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional Bio bio = 1;
 * @return {proto.portfolio.Bio}
 */
proto.portfolio.GetBioResponse.prototype.getBio = function() {
  return /** @type{proto.portfolio.Bio} */ (
    jspb.Message.getWrapperField(this, proto.portfolio.Bio, 1));
};


/** @param {proto.portfolio.Bio|undefined} value  */
proto.portfolio.GetBioResponse.prototype.setBio = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.portfolio.GetBioResponse.prototype.clearBio = function() {
  this.setBio(undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.portfolio.GetBioResponse.prototype.hasBio = function() {
  return jspb.Message.getField(this, 1) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.portfolio.GetBioRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.portfolio.GetBioRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.portfolio.GetBioRequest.displayName = 'proto.portfolio.GetBioRequest';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.portfolio.GetBioRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.portfolio.GetBioRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.portfolio.GetBioRequest} msg The msg instance to transform.
 * @return {!Object}
 */
proto.portfolio.GetBioRequest.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.portfolio.GetBioRequest}
 */
proto.portfolio.GetBioRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.portfolio.GetBioRequest;
  return proto.portfolio.GetBioRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.portfolio.GetBioRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.portfolio.GetBioRequest}
 */
proto.portfolio.GetBioRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.portfolio.GetBioRequest} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.portfolio.GetBioRequest.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.portfolio.GetBioRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.portfolio.GetBioRequest.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
};


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.portfolio.GetBioRequest} The clone.
 */
proto.portfolio.GetBioRequest.prototype.cloneMessage = function() {
  return /** @type {!proto.portfolio.GetBioRequest} */ (jspb.Message.cloneMessage(this));
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.portfolio.GetCVResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.portfolio.GetCVResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.portfolio.GetCVResponse.displayName = 'proto.portfolio.GetCVResponse';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.portfolio.GetCVResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.portfolio.GetCVResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.portfolio.GetCVResponse} msg The msg instance to transform.
 * @return {!Object}
 */
proto.portfolio.GetCVResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    skills: (f = msg.getSkills()) && proto.portfolio.Skills.toObject(includeInstance, f),
    jobs: (f = msg.getJobs()) && proto.portfolio.Experience.toObject(includeInstance, f),
    courses: (f = msg.getCourses()) && proto.portfolio.Education.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.portfolio.GetCVResponse}
 */
proto.portfolio.GetCVResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.portfolio.GetCVResponse;
  return proto.portfolio.GetCVResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.portfolio.GetCVResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.portfolio.GetCVResponse}
 */
proto.portfolio.GetCVResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.portfolio.Skills;
      reader.readMessage(value,proto.portfolio.Skills.deserializeBinaryFromReader);
      msg.setSkills(value);
      break;
    case 2:
      var value = new proto.portfolio.Experience;
      reader.readMessage(value,proto.portfolio.Experience.deserializeBinaryFromReader);
      msg.setJobs(value);
      break;
    case 3:
      var value = new proto.portfolio.Education;
      reader.readMessage(value,proto.portfolio.Education.deserializeBinaryFromReader);
      msg.setCourses(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.portfolio.GetCVResponse} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.portfolio.GetCVResponse.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.portfolio.GetCVResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.portfolio.GetCVResponse.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getSkills();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.portfolio.Skills.serializeBinaryToWriter
    );
  }
  f = this.getJobs();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.portfolio.Experience.serializeBinaryToWriter
    );
  }
  f = this.getCourses();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.portfolio.Education.serializeBinaryToWriter
    );
  }
};


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.portfolio.GetCVResponse} The clone.
 */
proto.portfolio.GetCVResponse.prototype.cloneMessage = function() {
  return /** @type {!proto.portfolio.GetCVResponse} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional Skills skills = 1;
 * @return {proto.portfolio.Skills}
 */
proto.portfolio.GetCVResponse.prototype.getSkills = function() {
  return /** @type{proto.portfolio.Skills} */ (
    jspb.Message.getWrapperField(this, proto.portfolio.Skills, 1));
};


/** @param {proto.portfolio.Skills|undefined} value  */
proto.portfolio.GetCVResponse.prototype.setSkills = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.portfolio.GetCVResponse.prototype.clearSkills = function() {
  this.setSkills(undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.portfolio.GetCVResponse.prototype.hasSkills = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional Experience jobs = 2;
 * @return {proto.portfolio.Experience}
 */
proto.portfolio.GetCVResponse.prototype.getJobs = function() {
  return /** @type{proto.portfolio.Experience} */ (
    jspb.Message.getWrapperField(this, proto.portfolio.Experience, 2));
};


/** @param {proto.portfolio.Experience|undefined} value  */
proto.portfolio.GetCVResponse.prototype.setJobs = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.portfolio.GetCVResponse.prototype.clearJobs = function() {
  this.setJobs(undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.portfolio.GetCVResponse.prototype.hasJobs = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional Education courses = 3;
 * @return {proto.portfolio.Education}
 */
proto.portfolio.GetCVResponse.prototype.getCourses = function() {
  return /** @type{proto.portfolio.Education} */ (
    jspb.Message.getWrapperField(this, proto.portfolio.Education, 3));
};


/** @param {proto.portfolio.Education|undefined} value  */
proto.portfolio.GetCVResponse.prototype.setCourses = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


proto.portfolio.GetCVResponse.prototype.clearCourses = function() {
  this.setCourses(undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.portfolio.GetCVResponse.prototype.hasCourses = function() {
  return jspb.Message.getField(this, 3) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.portfolio.GetCVRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.portfolio.GetCVRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.portfolio.GetCVRequest.displayName = 'proto.portfolio.GetCVRequest';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.portfolio.GetCVRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.portfolio.GetCVRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.portfolio.GetCVRequest} msg The msg instance to transform.
 * @return {!Object}
 */
proto.portfolio.GetCVRequest.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.portfolio.GetCVRequest}
 */
proto.portfolio.GetCVRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.portfolio.GetCVRequest;
  return proto.portfolio.GetCVRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.portfolio.GetCVRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.portfolio.GetCVRequest}
 */
proto.portfolio.GetCVRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.portfolio.GetCVRequest} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.portfolio.GetCVRequest.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.portfolio.GetCVRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.portfolio.GetCVRequest.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
};


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.portfolio.GetCVRequest} The clone.
 */
proto.portfolio.GetCVRequest.prototype.cloneMessage = function() {
  return /** @type {!proto.portfolio.GetCVRequest} */ (jspb.Message.cloneMessage(this));
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.portfolio.ListProjectsResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.portfolio.ListProjectsResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.portfolio.ListProjectsResponse.displayName = 'proto.portfolio.ListProjectsResponse';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.portfolio.ListProjectsResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.portfolio.ListProjectsResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.portfolio.ListProjectsResponse} msg The msg instance to transform.
 * @return {!Object}
 */
proto.portfolio.ListProjectsResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    projects: (f = msg.getProjects()) && proto.portfolio.Projects.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.portfolio.ListProjectsResponse}
 */
proto.portfolio.ListProjectsResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.portfolio.ListProjectsResponse;
  return proto.portfolio.ListProjectsResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.portfolio.ListProjectsResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.portfolio.ListProjectsResponse}
 */
proto.portfolio.ListProjectsResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.portfolio.Projects;
      reader.readMessage(value,proto.portfolio.Projects.deserializeBinaryFromReader);
      msg.setProjects(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.portfolio.ListProjectsResponse} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.portfolio.ListProjectsResponse.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.portfolio.ListProjectsResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.portfolio.ListProjectsResponse.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getProjects();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.portfolio.Projects.serializeBinaryToWriter
    );
  }
};


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.portfolio.ListProjectsResponse} The clone.
 */
proto.portfolio.ListProjectsResponse.prototype.cloneMessage = function() {
  return /** @type {!proto.portfolio.ListProjectsResponse} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional Projects projects = 1;
 * @return {proto.portfolio.Projects}
 */
proto.portfolio.ListProjectsResponse.prototype.getProjects = function() {
  return /** @type{proto.portfolio.Projects} */ (
    jspb.Message.getWrapperField(this, proto.portfolio.Projects, 1));
};


/** @param {proto.portfolio.Projects|undefined} value  */
proto.portfolio.ListProjectsResponse.prototype.setProjects = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.portfolio.ListProjectsResponse.prototype.clearProjects = function() {
  this.setProjects(undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.portfolio.ListProjectsResponse.prototype.hasProjects = function() {
  return jspb.Message.getField(this, 1) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.portfolio.ListProjectsRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.portfolio.ListProjectsRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.portfolio.ListProjectsRequest.displayName = 'proto.portfolio.ListProjectsRequest';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.portfolio.ListProjectsRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.portfolio.ListProjectsRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.portfolio.ListProjectsRequest} msg The msg instance to transform.
 * @return {!Object}
 */
proto.portfolio.ListProjectsRequest.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.portfolio.ListProjectsRequest}
 */
proto.portfolio.ListProjectsRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.portfolio.ListProjectsRequest;
  return proto.portfolio.ListProjectsRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.portfolio.ListProjectsRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.portfolio.ListProjectsRequest}
 */
proto.portfolio.ListProjectsRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.portfolio.ListProjectsRequest} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.portfolio.ListProjectsRequest.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.portfolio.ListProjectsRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.portfolio.ListProjectsRequest.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
};


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.portfolio.ListProjectsRequest} The clone.
 */
proto.portfolio.ListProjectsRequest.prototype.cloneMessage = function() {
  return /** @type {!proto.portfolio.ListProjectsRequest} */ (jspb.Message.cloneMessage(this));
};


goog.object.extend(exports, proto.portfolio);
