// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/portfolio.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Bio struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Bio) Reset()         { *m = Bio{} }
func (m *Bio) String() string { return proto.CompactTextString(m) }
func (*Bio) ProtoMessage()    {}
func (*Bio) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7973498bfb7f266, []int{0}
}
func (m *Bio) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bio.Unmarshal(m, b)
}
func (m *Bio) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bio.Marshal(b, m, deterministic)
}
func (m *Bio) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bio.Merge(m, src)
}
func (m *Bio) XXX_Size() int {
	return xxx_messageInfo_Bio.Size(m)
}
func (m *Bio) XXX_DiscardUnknown() {
	xxx_messageInfo_Bio.DiscardUnknown(m)
}

var xxx_messageInfo_Bio proto.InternalMessageInfo

func (m *Bio) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Bio) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type Course struct {
	ID                   uint32   `protobuf:"varint,1,opt,name=ID,json=iD,proto3" json:"ID,omitempty"`
	Institution          string   `protobuf:"bytes,2,opt,name=institution,proto3" json:"institution,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Dates                string   `protobuf:"bytes,4,opt,name=dates,proto3" json:"dates,omitempty"`
	Name                 string   `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Course) Reset()         { *m = Course{} }
func (m *Course) String() string { return proto.CompactTextString(m) }
func (*Course) ProtoMessage()    {}
func (*Course) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7973498bfb7f266, []int{1}
}
func (m *Course) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Course.Unmarshal(m, b)
}
func (m *Course) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Course.Marshal(b, m, deterministic)
}
func (m *Course) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Course.Merge(m, src)
}
func (m *Course) XXX_Size() int {
	return xxx_messageInfo_Course.Size(m)
}
func (m *Course) XXX_DiscardUnknown() {
	xxx_messageInfo_Course.DiscardUnknown(m)
}

var xxx_messageInfo_Course proto.InternalMessageInfo

func (m *Course) GetID() uint32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Course) GetInstitution() string {
	if m != nil {
		return m.Institution
	}
	return ""
}

func (m *Course) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Course) GetDates() string {
	if m != nil {
		return m.Dates
	}
	return ""
}

func (m *Course) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Education struct {
	Courses              []*Course `protobuf:"bytes,1,rep,name=courses,proto3" json:"courses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Education) Reset()         { *m = Education{} }
func (m *Education) String() string { return proto.CompactTextString(m) }
func (*Education) ProtoMessage()    {}
func (*Education) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7973498bfb7f266, []int{2}
}
func (m *Education) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Education.Unmarshal(m, b)
}
func (m *Education) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Education.Marshal(b, m, deterministic)
}
func (m *Education) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Education.Merge(m, src)
}
func (m *Education) XXX_Size() int {
	return xxx_messageInfo_Education.Size(m)
}
func (m *Education) XXX_DiscardUnknown() {
	xxx_messageInfo_Education.DiscardUnknown(m)
}

var xxx_messageInfo_Education proto.InternalMessageInfo

func (m *Education) GetCourses() []*Course {
	if m != nil {
		return m.Courses
	}
	return nil
}

type Skill struct {
	ID                   uint32   `protobuf:"varint,1,opt,name=ID,json=iD,proto3" json:"ID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Rating               uint32   `protobuf:"varint,3,opt,name=rating,proto3" json:"rating,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Skill) Reset()         { *m = Skill{} }
func (m *Skill) String() string { return proto.CompactTextString(m) }
func (*Skill) ProtoMessage()    {}
func (*Skill) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7973498bfb7f266, []int{3}
}
func (m *Skill) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Skill.Unmarshal(m, b)
}
func (m *Skill) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Skill.Marshal(b, m, deterministic)
}
func (m *Skill) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Skill.Merge(m, src)
}
func (m *Skill) XXX_Size() int {
	return xxx_messageInfo_Skill.Size(m)
}
func (m *Skill) XXX_DiscardUnknown() {
	xxx_messageInfo_Skill.DiscardUnknown(m)
}

var xxx_messageInfo_Skill proto.InternalMessageInfo

func (m *Skill) GetID() uint32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Skill) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Skill) GetRating() uint32 {
	if m != nil {
		return m.Rating
	}
	return 0
}

func (m *Skill) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type Skills struct {
	Skills               []*Skill `protobuf:"bytes,1,rep,name=skills,proto3" json:"skills,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Skills) Reset()         { *m = Skills{} }
func (m *Skills) String() string { return proto.CompactTextString(m) }
func (*Skills) ProtoMessage()    {}
func (*Skills) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7973498bfb7f266, []int{4}
}
func (m *Skills) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Skills.Unmarshal(m, b)
}
func (m *Skills) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Skills.Marshal(b, m, deterministic)
}
func (m *Skills) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Skills.Merge(m, src)
}
func (m *Skills) XXX_Size() int {
	return xxx_messageInfo_Skills.Size(m)
}
func (m *Skills) XXX_DiscardUnknown() {
	xxx_messageInfo_Skills.DiscardUnknown(m)
}

var xxx_messageInfo_Skills proto.InternalMessageInfo

func (m *Skills) GetSkills() []*Skill {
	if m != nil {
		return m.Skills
	}
	return nil
}

type Project struct {
	ID                   uint32   `protobuf:"varint,1,opt,name=ID,json=iD,proto3" json:"ID,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Meta                 string   `protobuf:"bytes,3,opt,name=meta,proto3" json:"meta,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Repo                 string   `protobuf:"bytes,5,opt,name=repo,proto3" json:"repo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Project) Reset()         { *m = Project{} }
func (m *Project) String() string { return proto.CompactTextString(m) }
func (*Project) ProtoMessage()    {}
func (*Project) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7973498bfb7f266, []int{5}
}
func (m *Project) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Project.Unmarshal(m, b)
}
func (m *Project) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Project.Marshal(b, m, deterministic)
}
func (m *Project) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Project.Merge(m, src)
}
func (m *Project) XXX_Size() int {
	return xxx_messageInfo_Project.Size(m)
}
func (m *Project) XXX_DiscardUnknown() {
	xxx_messageInfo_Project.DiscardUnknown(m)
}

var xxx_messageInfo_Project proto.InternalMessageInfo

func (m *Project) GetID() uint32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Project) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Project) GetMeta() string {
	if m != nil {
		return m.Meta
	}
	return ""
}

func (m *Project) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Project) GetRepo() string {
	if m != nil {
		return m.Repo
	}
	return ""
}

type Projects struct {
	Projects             []*Project `protobuf:"bytes,1,rep,name=projects,proto3" json:"projects,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Projects) Reset()         { *m = Projects{} }
func (m *Projects) String() string { return proto.CompactTextString(m) }
func (*Projects) ProtoMessage()    {}
func (*Projects) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7973498bfb7f266, []int{6}
}
func (m *Projects) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Projects.Unmarshal(m, b)
}
func (m *Projects) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Projects.Marshal(b, m, deterministic)
}
func (m *Projects) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Projects.Merge(m, src)
}
func (m *Projects) XXX_Size() int {
	return xxx_messageInfo_Projects.Size(m)
}
func (m *Projects) XXX_DiscardUnknown() {
	xxx_messageInfo_Projects.DiscardUnknown(m)
}

var xxx_messageInfo_Projects proto.InternalMessageInfo

func (m *Projects) GetProjects() []*Project {
	if m != nil {
		return m.Projects
	}
	return nil
}

type Job struct {
	ID                   uint32   `protobuf:"varint,1,opt,name=ID,json=iD,proto3" json:"ID,omitempty"`
	Company              string   `protobuf:"bytes,2,opt,name=company,proto3" json:"company,omitempty"`
	JobTitle             string   `protobuf:"bytes,3,opt,name=job_title,json=jobTitle,proto3" json:"job_title,omitempty"`
	Location             string   `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	Dates                string   `protobuf:"bytes,5,opt,name=dates,proto3" json:"dates,omitempty"`
	Description          string   `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	LogoUrl              string   `protobuf:"bytes,7,opt,name=logo_url,json=logoUrl,proto3" json:"logo_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Job) Reset()         { *m = Job{} }
func (m *Job) String() string { return proto.CompactTextString(m) }
func (*Job) ProtoMessage()    {}
func (*Job) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7973498bfb7f266, []int{7}
}
func (m *Job) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Job.Unmarshal(m, b)
}
func (m *Job) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Job.Marshal(b, m, deterministic)
}
func (m *Job) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Job.Merge(m, src)
}
func (m *Job) XXX_Size() int {
	return xxx_messageInfo_Job.Size(m)
}
func (m *Job) XXX_DiscardUnknown() {
	xxx_messageInfo_Job.DiscardUnknown(m)
}

var xxx_messageInfo_Job proto.InternalMessageInfo

func (m *Job) GetID() uint32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Job) GetCompany() string {
	if m != nil {
		return m.Company
	}
	return ""
}

func (m *Job) GetJobTitle() string {
	if m != nil {
		return m.JobTitle
	}
	return ""
}

func (m *Job) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *Job) GetDates() string {
	if m != nil {
		return m.Dates
	}
	return ""
}

func (m *Job) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Job) GetLogoUrl() string {
	if m != nil {
		return m.LogoUrl
	}
	return ""
}

type Experience struct {
	Jobs                 []*Job   `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Experience) Reset()         { *m = Experience{} }
func (m *Experience) String() string { return proto.CompactTextString(m) }
func (*Experience) ProtoMessage()    {}
func (*Experience) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7973498bfb7f266, []int{8}
}
func (m *Experience) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Experience.Unmarshal(m, b)
}
func (m *Experience) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Experience.Marshal(b, m, deterministic)
}
func (m *Experience) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Experience.Merge(m, src)
}
func (m *Experience) XXX_Size() int {
	return xxx_messageInfo_Experience.Size(m)
}
func (m *Experience) XXX_DiscardUnknown() {
	xxx_messageInfo_Experience.DiscardUnknown(m)
}

var xxx_messageInfo_Experience proto.InternalMessageInfo

func (m *Experience) GetJobs() []*Job {
	if m != nil {
		return m.Jobs
	}
	return nil
}

type AddBioResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddBioResponse) Reset()         { *m = AddBioResponse{} }
func (m *AddBioResponse) String() string { return proto.CompactTextString(m) }
func (*AddBioResponse) ProtoMessage()    {}
func (*AddBioResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7973498bfb7f266, []int{9}
}
func (m *AddBioResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddBioResponse.Unmarshal(m, b)
}
func (m *AddBioResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddBioResponse.Marshal(b, m, deterministic)
}
func (m *AddBioResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddBioResponse.Merge(m, src)
}
func (m *AddBioResponse) XXX_Size() int {
	return xxx_messageInfo_AddBioResponse.Size(m)
}
func (m *AddBioResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddBioResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddBioResponse proto.InternalMessageInfo

type AddBioRequest struct {
	Bio                  *Bio     `protobuf:"bytes,1,opt,name=bio,proto3" json:"bio,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddBioRequest) Reset()         { *m = AddBioRequest{} }
func (m *AddBioRequest) String() string { return proto.CompactTextString(m) }
func (*AddBioRequest) ProtoMessage()    {}
func (*AddBioRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7973498bfb7f266, []int{10}
}
func (m *AddBioRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddBioRequest.Unmarshal(m, b)
}
func (m *AddBioRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddBioRequest.Marshal(b, m, deterministic)
}
func (m *AddBioRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddBioRequest.Merge(m, src)
}
func (m *AddBioRequest) XXX_Size() int {
	return xxx_messageInfo_AddBioRequest.Size(m)
}
func (m *AddBioRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddBioRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddBioRequest proto.InternalMessageInfo

func (m *AddBioRequest) GetBio() *Bio {
	if m != nil {
		return m.Bio
	}
	return nil
}

type AddCourseResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddCourseResponse) Reset()         { *m = AddCourseResponse{} }
func (m *AddCourseResponse) String() string { return proto.CompactTextString(m) }
func (*AddCourseResponse) ProtoMessage()    {}
func (*AddCourseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7973498bfb7f266, []int{11}
}
func (m *AddCourseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddCourseResponse.Unmarshal(m, b)
}
func (m *AddCourseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddCourseResponse.Marshal(b, m, deterministic)
}
func (m *AddCourseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddCourseResponse.Merge(m, src)
}
func (m *AddCourseResponse) XXX_Size() int {
	return xxx_messageInfo_AddCourseResponse.Size(m)
}
func (m *AddCourseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddCourseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddCourseResponse proto.InternalMessageInfo

type AddCourseRequest struct {
	Course               *Course  `protobuf:"bytes,1,opt,name=course,proto3" json:"course,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddCourseRequest) Reset()         { *m = AddCourseRequest{} }
func (m *AddCourseRequest) String() string { return proto.CompactTextString(m) }
func (*AddCourseRequest) ProtoMessage()    {}
func (*AddCourseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7973498bfb7f266, []int{12}
}
func (m *AddCourseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddCourseRequest.Unmarshal(m, b)
}
func (m *AddCourseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddCourseRequest.Marshal(b, m, deterministic)
}
func (m *AddCourseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddCourseRequest.Merge(m, src)
}
func (m *AddCourseRequest) XXX_Size() int {
	return xxx_messageInfo_AddCourseRequest.Size(m)
}
func (m *AddCourseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddCourseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddCourseRequest proto.InternalMessageInfo

func (m *AddCourseRequest) GetCourse() *Course {
	if m != nil {
		return m.Course
	}
	return nil
}

type AddJobResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddJobResponse) Reset()         { *m = AddJobResponse{} }
func (m *AddJobResponse) String() string { return proto.CompactTextString(m) }
func (*AddJobResponse) ProtoMessage()    {}
func (*AddJobResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7973498bfb7f266, []int{13}
}
func (m *AddJobResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddJobResponse.Unmarshal(m, b)
}
func (m *AddJobResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddJobResponse.Marshal(b, m, deterministic)
}
func (m *AddJobResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddJobResponse.Merge(m, src)
}
func (m *AddJobResponse) XXX_Size() int {
	return xxx_messageInfo_AddJobResponse.Size(m)
}
func (m *AddJobResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddJobResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddJobResponse proto.InternalMessageInfo

type AddJobRequest struct {
	Job                  *Job     `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddJobRequest) Reset()         { *m = AddJobRequest{} }
func (m *AddJobRequest) String() string { return proto.CompactTextString(m) }
func (*AddJobRequest) ProtoMessage()    {}
func (*AddJobRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7973498bfb7f266, []int{14}
}
func (m *AddJobRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddJobRequest.Unmarshal(m, b)
}
func (m *AddJobRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddJobRequest.Marshal(b, m, deterministic)
}
func (m *AddJobRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddJobRequest.Merge(m, src)
}
func (m *AddJobRequest) XXX_Size() int {
	return xxx_messageInfo_AddJobRequest.Size(m)
}
func (m *AddJobRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddJobRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddJobRequest proto.InternalMessageInfo

func (m *AddJobRequest) GetJob() *Job {
	if m != nil {
		return m.Job
	}
	return nil
}

type AddProjectResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddProjectResponse) Reset()         { *m = AddProjectResponse{} }
func (m *AddProjectResponse) String() string { return proto.CompactTextString(m) }
func (*AddProjectResponse) ProtoMessage()    {}
func (*AddProjectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7973498bfb7f266, []int{15}
}
func (m *AddProjectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddProjectResponse.Unmarshal(m, b)
}
func (m *AddProjectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddProjectResponse.Marshal(b, m, deterministic)
}
func (m *AddProjectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddProjectResponse.Merge(m, src)
}
func (m *AddProjectResponse) XXX_Size() int {
	return xxx_messageInfo_AddProjectResponse.Size(m)
}
func (m *AddProjectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddProjectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddProjectResponse proto.InternalMessageInfo

type AddProjectRequest struct {
	Project              *Project `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddProjectRequest) Reset()         { *m = AddProjectRequest{} }
func (m *AddProjectRequest) String() string { return proto.CompactTextString(m) }
func (*AddProjectRequest) ProtoMessage()    {}
func (*AddProjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7973498bfb7f266, []int{16}
}
func (m *AddProjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddProjectRequest.Unmarshal(m, b)
}
func (m *AddProjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddProjectRequest.Marshal(b, m, deterministic)
}
func (m *AddProjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddProjectRequest.Merge(m, src)
}
func (m *AddProjectRequest) XXX_Size() int {
	return xxx_messageInfo_AddProjectRequest.Size(m)
}
func (m *AddProjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddProjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddProjectRequest proto.InternalMessageInfo

func (m *AddProjectRequest) GetProject() *Project {
	if m != nil {
		return m.Project
	}
	return nil
}

type AddSkillResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddSkillResponse) Reset()         { *m = AddSkillResponse{} }
func (m *AddSkillResponse) String() string { return proto.CompactTextString(m) }
func (*AddSkillResponse) ProtoMessage()    {}
func (*AddSkillResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7973498bfb7f266, []int{17}
}
func (m *AddSkillResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddSkillResponse.Unmarshal(m, b)
}
func (m *AddSkillResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddSkillResponse.Marshal(b, m, deterministic)
}
func (m *AddSkillResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddSkillResponse.Merge(m, src)
}
func (m *AddSkillResponse) XXX_Size() int {
	return xxx_messageInfo_AddSkillResponse.Size(m)
}
func (m *AddSkillResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddSkillResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddSkillResponse proto.InternalMessageInfo

type AddSkillRequest struct {
	Skill                *Skill   `protobuf:"bytes,1,opt,name=skill,proto3" json:"skill,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddSkillRequest) Reset()         { *m = AddSkillRequest{} }
func (m *AddSkillRequest) String() string { return proto.CompactTextString(m) }
func (*AddSkillRequest) ProtoMessage()    {}
func (*AddSkillRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7973498bfb7f266, []int{18}
}
func (m *AddSkillRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddSkillRequest.Unmarshal(m, b)
}
func (m *AddSkillRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddSkillRequest.Marshal(b, m, deterministic)
}
func (m *AddSkillRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddSkillRequest.Merge(m, src)
}
func (m *AddSkillRequest) XXX_Size() int {
	return xxx_messageInfo_AddSkillRequest.Size(m)
}
func (m *AddSkillRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddSkillRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddSkillRequest proto.InternalMessageInfo

func (m *AddSkillRequest) GetSkill() *Skill {
	if m != nil {
		return m.Skill
	}
	return nil
}

type GetBioResponse struct {
	Bio                  *Bio     `protobuf:"bytes,1,opt,name=bio,proto3" json:"bio,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBioResponse) Reset()         { *m = GetBioResponse{} }
func (m *GetBioResponse) String() string { return proto.CompactTextString(m) }
func (*GetBioResponse) ProtoMessage()    {}
func (*GetBioResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7973498bfb7f266, []int{19}
}
func (m *GetBioResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBioResponse.Unmarshal(m, b)
}
func (m *GetBioResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBioResponse.Marshal(b, m, deterministic)
}
func (m *GetBioResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBioResponse.Merge(m, src)
}
func (m *GetBioResponse) XXX_Size() int {
	return xxx_messageInfo_GetBioResponse.Size(m)
}
func (m *GetBioResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBioResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBioResponse proto.InternalMessageInfo

func (m *GetBioResponse) GetBio() *Bio {
	if m != nil {
		return m.Bio
	}
	return nil
}

type GetBioRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBioRequest) Reset()         { *m = GetBioRequest{} }
func (m *GetBioRequest) String() string { return proto.CompactTextString(m) }
func (*GetBioRequest) ProtoMessage()    {}
func (*GetBioRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7973498bfb7f266, []int{20}
}
func (m *GetBioRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBioRequest.Unmarshal(m, b)
}
func (m *GetBioRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBioRequest.Marshal(b, m, deterministic)
}
func (m *GetBioRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBioRequest.Merge(m, src)
}
func (m *GetBioRequest) XXX_Size() int {
	return xxx_messageInfo_GetBioRequest.Size(m)
}
func (m *GetBioRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBioRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBioRequest proto.InternalMessageInfo

type GetCVResponse struct {
	Skills               *Skills     `protobuf:"bytes,1,opt,name=skills,proto3" json:"skills,omitempty"`
	Jobs                 *Experience `protobuf:"bytes,2,opt,name=jobs,proto3" json:"jobs,omitempty"`
	Courses              *Education  `protobuf:"bytes,3,opt,name=courses,proto3" json:"courses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetCVResponse) Reset()         { *m = GetCVResponse{} }
func (m *GetCVResponse) String() string { return proto.CompactTextString(m) }
func (*GetCVResponse) ProtoMessage()    {}
func (*GetCVResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7973498bfb7f266, []int{21}
}
func (m *GetCVResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCVResponse.Unmarshal(m, b)
}
func (m *GetCVResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCVResponse.Marshal(b, m, deterministic)
}
func (m *GetCVResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCVResponse.Merge(m, src)
}
func (m *GetCVResponse) XXX_Size() int {
	return xxx_messageInfo_GetCVResponse.Size(m)
}
func (m *GetCVResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCVResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCVResponse proto.InternalMessageInfo

func (m *GetCVResponse) GetSkills() *Skills {
	if m != nil {
		return m.Skills
	}
	return nil
}

func (m *GetCVResponse) GetJobs() *Experience {
	if m != nil {
		return m.Jobs
	}
	return nil
}

func (m *GetCVResponse) GetCourses() *Education {
	if m != nil {
		return m.Courses
	}
	return nil
}

type GetCVRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCVRequest) Reset()         { *m = GetCVRequest{} }
func (m *GetCVRequest) String() string { return proto.CompactTextString(m) }
func (*GetCVRequest) ProtoMessage()    {}
func (*GetCVRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7973498bfb7f266, []int{22}
}
func (m *GetCVRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCVRequest.Unmarshal(m, b)
}
func (m *GetCVRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCVRequest.Marshal(b, m, deterministic)
}
func (m *GetCVRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCVRequest.Merge(m, src)
}
func (m *GetCVRequest) XXX_Size() int {
	return xxx_messageInfo_GetCVRequest.Size(m)
}
func (m *GetCVRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCVRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCVRequest proto.InternalMessageInfo

type ListProjectsResponse struct {
	Projects             *Projects `protobuf:"bytes,1,opt,name=projects,proto3" json:"projects,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ListProjectsResponse) Reset()         { *m = ListProjectsResponse{} }
func (m *ListProjectsResponse) String() string { return proto.CompactTextString(m) }
func (*ListProjectsResponse) ProtoMessage()    {}
func (*ListProjectsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7973498bfb7f266, []int{23}
}
func (m *ListProjectsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListProjectsResponse.Unmarshal(m, b)
}
func (m *ListProjectsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListProjectsResponse.Marshal(b, m, deterministic)
}
func (m *ListProjectsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListProjectsResponse.Merge(m, src)
}
func (m *ListProjectsResponse) XXX_Size() int {
	return xxx_messageInfo_ListProjectsResponse.Size(m)
}
func (m *ListProjectsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListProjectsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListProjectsResponse proto.InternalMessageInfo

func (m *ListProjectsResponse) GetProjects() *Projects {
	if m != nil {
		return m.Projects
	}
	return nil
}

type ListProjectsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListProjectsRequest) Reset()         { *m = ListProjectsRequest{} }
func (m *ListProjectsRequest) String() string { return proto.CompactTextString(m) }
func (*ListProjectsRequest) ProtoMessage()    {}
func (*ListProjectsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7973498bfb7f266, []int{24}
}
func (m *ListProjectsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListProjectsRequest.Unmarshal(m, b)
}
func (m *ListProjectsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListProjectsRequest.Marshal(b, m, deterministic)
}
func (m *ListProjectsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListProjectsRequest.Merge(m, src)
}
func (m *ListProjectsRequest) XXX_Size() int {
	return xxx_messageInfo_ListProjectsRequest.Size(m)
}
func (m *ListProjectsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListProjectsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListProjectsRequest proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Bio)(nil), "proto.Bio")
	proto.RegisterType((*Course)(nil), "proto.Course")
	proto.RegisterType((*Education)(nil), "proto.Education")
	proto.RegisterType((*Skill)(nil), "proto.Skill")
	proto.RegisterType((*Skills)(nil), "proto.Skills")
	proto.RegisterType((*Project)(nil), "proto.Project")
	proto.RegisterType((*Projects)(nil), "proto.Projects")
	proto.RegisterType((*Job)(nil), "proto.Job")
	proto.RegisterType((*Experience)(nil), "proto.Experience")
	proto.RegisterType((*AddBioResponse)(nil), "proto.AddBioResponse")
	proto.RegisterType((*AddBioRequest)(nil), "proto.AddBioRequest")
	proto.RegisterType((*AddCourseResponse)(nil), "proto.AddCourseResponse")
	proto.RegisterType((*AddCourseRequest)(nil), "proto.AddCourseRequest")
	proto.RegisterType((*AddJobResponse)(nil), "proto.AddJobResponse")
	proto.RegisterType((*AddJobRequest)(nil), "proto.AddJobRequest")
	proto.RegisterType((*AddProjectResponse)(nil), "proto.AddProjectResponse")
	proto.RegisterType((*AddProjectRequest)(nil), "proto.AddProjectRequest")
	proto.RegisterType((*AddSkillResponse)(nil), "proto.AddSkillResponse")
	proto.RegisterType((*AddSkillRequest)(nil), "proto.AddSkillRequest")
	proto.RegisterType((*GetBioResponse)(nil), "proto.GetBioResponse")
	proto.RegisterType((*GetBioRequest)(nil), "proto.GetBioRequest")
	proto.RegisterType((*GetCVResponse)(nil), "proto.GetCVResponse")
	proto.RegisterType((*GetCVRequest)(nil), "proto.GetCVRequest")
	proto.RegisterType((*ListProjectsResponse)(nil), "proto.ListProjectsResponse")
	proto.RegisterType((*ListProjectsRequest)(nil), "proto.ListProjectsRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PortfolioServiceClient is the client API for PortfolioService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PortfolioServiceClient interface {
	AddBio(ctx context.Context, in *AddBioRequest, opts ...grpc.CallOption) (*AddBioResponse, error)
	AddCourse(ctx context.Context, in *AddCourseRequest, opts ...grpc.CallOption) (*AddCourseResponse, error)
	AddJob(ctx context.Context, in *AddJobRequest, opts ...grpc.CallOption) (*AddJobResponse, error)
	AddProject(ctx context.Context, in *AddProjectRequest, opts ...grpc.CallOption) (*AddProjectResponse, error)
	AddSkill(ctx context.Context, in *AddSkillRequest, opts ...grpc.CallOption) (*AddSkillResponse, error)
	GetBio(ctx context.Context, in *GetBioRequest, opts ...grpc.CallOption) (*GetBioResponse, error)
	GetCV(ctx context.Context, in *GetCVRequest, opts ...grpc.CallOption) (*GetCVResponse, error)
	ListProjects(ctx context.Context, in *ListProjectsRequest, opts ...grpc.CallOption) (*ListProjectsResponse, error)
}

type portfolioServiceClient struct {
	cc *grpc.ClientConn
}

func NewPortfolioServiceClient(cc *grpc.ClientConn) PortfolioServiceClient {
	return &portfolioServiceClient{cc}
}

func (c *portfolioServiceClient) AddBio(ctx context.Context, in *AddBioRequest, opts ...grpc.CallOption) (*AddBioResponse, error) {
	out := new(AddBioResponse)
	err := c.cc.Invoke(ctx, "/proto.PortfolioService/AddBio", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portfolioServiceClient) AddCourse(ctx context.Context, in *AddCourseRequest, opts ...grpc.CallOption) (*AddCourseResponse, error) {
	out := new(AddCourseResponse)
	err := c.cc.Invoke(ctx, "/proto.PortfolioService/AddCourse", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portfolioServiceClient) AddJob(ctx context.Context, in *AddJobRequest, opts ...grpc.CallOption) (*AddJobResponse, error) {
	out := new(AddJobResponse)
	err := c.cc.Invoke(ctx, "/proto.PortfolioService/AddJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portfolioServiceClient) AddProject(ctx context.Context, in *AddProjectRequest, opts ...grpc.CallOption) (*AddProjectResponse, error) {
	out := new(AddProjectResponse)
	err := c.cc.Invoke(ctx, "/proto.PortfolioService/AddProject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portfolioServiceClient) AddSkill(ctx context.Context, in *AddSkillRequest, opts ...grpc.CallOption) (*AddSkillResponse, error) {
	out := new(AddSkillResponse)
	err := c.cc.Invoke(ctx, "/proto.PortfolioService/AddSkill", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portfolioServiceClient) GetBio(ctx context.Context, in *GetBioRequest, opts ...grpc.CallOption) (*GetBioResponse, error) {
	out := new(GetBioResponse)
	err := c.cc.Invoke(ctx, "/proto.PortfolioService/GetBio", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portfolioServiceClient) GetCV(ctx context.Context, in *GetCVRequest, opts ...grpc.CallOption) (*GetCVResponse, error) {
	out := new(GetCVResponse)
	err := c.cc.Invoke(ctx, "/proto.PortfolioService/GetCV", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portfolioServiceClient) ListProjects(ctx context.Context, in *ListProjectsRequest, opts ...grpc.CallOption) (*ListProjectsResponse, error) {
	out := new(ListProjectsResponse)
	err := c.cc.Invoke(ctx, "/proto.PortfolioService/ListProjects", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PortfolioServiceServer is the server API for PortfolioService service.
type PortfolioServiceServer interface {
	AddBio(context.Context, *AddBioRequest) (*AddBioResponse, error)
	AddCourse(context.Context, *AddCourseRequest) (*AddCourseResponse, error)
	AddJob(context.Context, *AddJobRequest) (*AddJobResponse, error)
	AddProject(context.Context, *AddProjectRequest) (*AddProjectResponse, error)
	AddSkill(context.Context, *AddSkillRequest) (*AddSkillResponse, error)
	GetBio(context.Context, *GetBioRequest) (*GetBioResponse, error)
	GetCV(context.Context, *GetCVRequest) (*GetCVResponse, error)
	ListProjects(context.Context, *ListProjectsRequest) (*ListProjectsResponse, error)
}

func RegisterPortfolioServiceServer(s *grpc.Server, srv PortfolioServiceServer) {
	s.RegisterService(&_PortfolioService_serviceDesc, srv)
}

func _PortfolioService_AddBio_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddBioRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServiceServer).AddBio(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.PortfolioService/AddBio",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServiceServer).AddBio(ctx, req.(*AddBioRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortfolioService_AddCourse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddCourseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServiceServer).AddCourse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.PortfolioService/AddCourse",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServiceServer).AddCourse(ctx, req.(*AddCourseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortfolioService_AddJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServiceServer).AddJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.PortfolioService/AddJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServiceServer).AddJob(ctx, req.(*AddJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortfolioService_AddProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServiceServer).AddProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.PortfolioService/AddProject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServiceServer).AddProject(ctx, req.(*AddProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortfolioService_AddSkill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddSkillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServiceServer).AddSkill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.PortfolioService/AddSkill",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServiceServer).AddSkill(ctx, req.(*AddSkillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortfolioService_GetBio_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBioRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServiceServer).GetBio(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.PortfolioService/GetBio",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServiceServer).GetBio(ctx, req.(*GetBioRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortfolioService_GetCV_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCVRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServiceServer).GetCV(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.PortfolioService/GetCV",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServiceServer).GetCV(ctx, req.(*GetCVRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortfolioService_ListProjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProjectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServiceServer).ListProjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.PortfolioService/ListProjects",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServiceServer).ListProjects(ctx, req.(*ListProjectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PortfolioService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.PortfolioService",
	HandlerType: (*PortfolioServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddBio",
			Handler:    _PortfolioService_AddBio_Handler,
		},
		{
			MethodName: "AddCourse",
			Handler:    _PortfolioService_AddCourse_Handler,
		},
		{
			MethodName: "AddJob",
			Handler:    _PortfolioService_AddJob_Handler,
		},
		{
			MethodName: "AddProject",
			Handler:    _PortfolioService_AddProject_Handler,
		},
		{
			MethodName: "AddSkill",
			Handler:    _PortfolioService_AddSkill_Handler,
		},
		{
			MethodName: "GetBio",
			Handler:    _PortfolioService_GetBio_Handler,
		},
		{
			MethodName: "GetCV",
			Handler:    _PortfolioService_GetCV_Handler,
		},
		{
			MethodName: "ListProjects",
			Handler:    _PortfolioService_ListProjects_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/portfolio.proto",
}

func init() { proto.RegisterFile("proto/portfolio.proto", fileDescriptor_d7973498bfb7f266) }

var fileDescriptor_d7973498bfb7f266 = []byte{
	// 777 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x54, 0x6d, 0x4f, 0xdb, 0x3a,
	0x14, 0x56, 0xdf, 0xd2, 0xf6, 0x40, 0x4b, 0x31, 0x05, 0x42, 0xb8, 0xba, 0x42, 0xd6, 0x45, 0x17,
	0x71, 0xef, 0x3a, 0x89, 0x8d, 0x49, 0xd3, 0xc4, 0xa4, 0xf2, 0x22, 0x34, 0xb4, 0x0f, 0x28, 0x6c,
	0xfb, 0x8a, 0x9a, 0xc6, 0x43, 0xee, 0x4a, 0x9d, 0x25, 0xe9, 0x34, 0xfe, 0xc0, 0xa4, 0xfd, 0xa6,
	0xfd, 0xad, 0xfd, 0x80, 0xc9, 0xf6, 0x71, 0xe2, 0x24, 0x48, 0x7c, 0x4a, 0x7c, 0x9e, 0xe3, 0xc7,
	0xcf, 0x39, 0xe7, 0xb1, 0x61, 0x33, 0x8a, 0x45, 0x2a, 0x9e, 0x47, 0x22, 0x4e, 0x3f, 0x8b, 0x39,
	0x17, 0x23, 0xb5, 0x26, 0x2d, 0xf5, 0xa1, 0x27, 0xd0, 0x38, 0xe5, 0x82, 0x0c, 0xa1, 0x95, 0xf2,
	0x74, 0xce, 0xdc, 0xda, 0x5e, 0xed, 0xa0, 0xeb, 0xeb, 0x05, 0xd9, 0x83, 0x95, 0x90, 0x25, 0xd3,
	0x98, 0x47, 0x29, 0x17, 0x0b, 0xb7, 0xae, 0x30, 0x3b, 0x44, 0x7f, 0xd4, 0xc0, 0x39, 0x13, 0xcb,
	0x38, 0x61, 0xa4, 0x0f, 0xf5, 0x77, 0xe7, 0x6a, 0x7f, 0xcf, 0xaf, 0xf3, 0x73, 0xb9, 0x99, 0x2f,
	0x92, 0x94, 0xa7, 0x4b, 0x7b, 0xb3, 0x15, 0x2a, 0xd3, 0x37, 0x2a, 0xf4, 0x52, 0x56, 0x38, 0x49,
	0x59, 0xe2, 0x36, 0xb5, 0x2c, 0xb5, 0x20, 0x04, 0x9a, 0x8b, 0xc9, 0x3d, 0x73, 0x5b, 0x2a, 0xa8,
	0xfe, 0xe9, 0x4b, 0xe8, 0x5e, 0x84, 0xcb, 0xe9, 0x44, 0x6d, 0xfb, 0x17, 0xda, 0x53, 0x25, 0x2a,
	0x71, 0x6b, 0x7b, 0x8d, 0x83, 0x95, 0xa3, 0x9e, 0x2e, 0x7a, 0xa4, 0xa5, 0xfa, 0x06, 0xa5, 0x0c,
	0x5a, 0x37, 0x5f, 0xf8, 0x7c, 0x5e, 0x11, 0x6f, 0x8e, 0xa8, 0xe7, 0x47, 0x90, 0x2d, 0x70, 0xe2,
	0x49, 0xca, 0x17, 0x77, 0x4a, 0x69, 0xcf, 0xc7, 0x55, 0xb9, 0x8c, 0x66, 0xb5, 0x4b, 0x23, 0x70,
	0xd4, 0x31, 0x09, 0xf9, 0x07, 0x9c, 0x44, 0xfd, 0xa1, 0xb0, 0x55, 0x14, 0xa6, 0x60, 0x1f, 0x31,
	0xfa, 0x00, 0xed, 0xeb, 0x58, 0xcc, 0xd8, 0x34, 0xad, 0x08, 0xcb, 0x06, 0x55, 0xb7, 0x07, 0x45,
	0xa0, 0x79, 0xcf, 0xd2, 0x09, 0xb6, 0x50, 0xfd, 0x3f, 0x2d, 0x4b, 0xee, 0x8a, 0x59, 0x24, 0x4c,
	0x1f, 0xe5, 0x3f, 0x7d, 0x05, 0x1d, 0x3c, 0x3a, 0x21, 0x87, 0xd0, 0x89, 0xf0, 0x1f, 0xe5, 0xf6,
	0x51, 0x2e, 0xa6, 0xf8, 0x19, 0x4e, 0x7f, 0xd5, 0xa0, 0x71, 0x25, 0x82, 0x8a, 0x5e, 0x57, 0x8e,
	0xe2, 0x3e, 0x9a, 0x2c, 0x1e, 0x50, 0xb1, 0x59, 0x92, 0x5d, 0xe8, 0xce, 0x44, 0x70, 0xab, 0xab,
	0xd1, 0xc2, 0x3b, 0x33, 0x11, 0x7c, 0x50, 0x05, 0x79, 0xd0, 0x99, 0x0b, 0x3d, 0x4d, 0x54, 0x9e,
	0xad, 0x73, 0x53, 0xb4, 0x6c, 0x53, 0x94, 0xca, 0x75, 0xaa, 0xe5, 0xee, 0x48, 0xce, 0x3b, 0x71,
	0xbb, 0x8c, 0xe7, 0x6e, 0x5b, 0x6b, 0x91, 0xeb, 0x8f, 0xf1, 0x9c, 0xfe, 0x0f, 0x70, 0xf1, 0x3d,
	0x62, 0x31, 0x67, 0x8b, 0x29, 0x23, 0x7f, 0x43, 0x73, 0x26, 0x02, 0x53, 0x33, 0x60, 0xcd, 0x57,
	0x22, 0xf0, 0x55, 0x9c, 0x0e, 0xa0, 0x3f, 0x0e, 0xc3, 0x53, 0x2e, 0x7c, 0x96, 0x44, 0x62, 0x91,
	0x30, 0xfa, 0x0c, 0x7a, 0x26, 0xf2, 0x75, 0xc9, 0x92, 0x94, 0xfc, 0x05, 0x8d, 0x80, 0x0b, 0xd5,
	0x87, 0x9c, 0x41, 0xe2, 0x32, 0x4c, 0x37, 0x60, 0x7d, 0x1c, 0x86, 0x68, 0x46, 0xc3, 0xf1, 0x1a,
	0x06, 0x56, 0x50, 0xd3, 0xec, 0x83, 0xa3, 0xad, 0x8a, 0x4c, 0x25, 0x1f, 0x23, 0x88, 0x82, 0xa4,
	0xc0, 0xa2, 0x20, 0x15, 0xc9, 0x04, 0xcd, 0x44, 0x50, 0x12, 0x24, 0x71, 0x19, 0xa6, 0x43, 0x20,
	0xe3, 0x30, 0x34, 0x53, 0x35, 0x24, 0x27, 0x4a, 0x66, 0x16, 0xd5, 0x44, 0x07, 0xd0, 0xc6, 0xa1,
	0x23, 0x59, 0xd9, 0x13, 0x06, 0xa6, 0x44, 0x15, 0xa4, 0x9d, 0x6d, 0x28, 0x8f, 0x61, 0x2d, 0x8f,
	0x69, 0x42, 0x0a, 0x2d, 0x65, 0x7b, 0xa4, 0x2b, 0xde, 0x08, 0x0d, 0xd1, 0x11, 0xf4, 0x2f, 0x59,
	0x6a, 0x75, 0xfc, 0x89, 0x06, 0xaf, 0x41, 0xcf, 0xe4, 0xab, 0x43, 0xe8, 0xcf, 0x9a, 0x8a, 0x9c,
	0x7d, 0xca, 0x08, 0xf6, 0xad, 0x9b, 0x68, 0xb7, 0x56, 0x5f, 0x54, 0x73, 0x15, 0xc9, 0x3e, 0x7a,
	0xa1, 0xae, 0x92, 0xd6, 0x31, 0x29, 0x37, 0x8b, 0xb6, 0x04, 0x39, 0xcc, 0x5f, 0x9c, 0x86, 0xca,
	0x1c, 0x98, 0x4c, 0xf3, 0x28, 0xe5, 0x8f, 0x4e, 0x1f, 0x56, 0x51, 0x8a, 0xd6, 0x76, 0x06, 0xc3,
	0xf7, 0x3c, 0x49, 0xcd, 0xb5, 0xcb, 0x14, 0xfe, 0x57, 0xb8, 0x7e, 0x92, 0x74, 0xad, 0xd8, 0xea,
	0xc4, 0xba, 0x7f, 0x9b, 0xb0, 0x51, 0x24, 0x51, 0xdc, 0x47, 0xbf, 0x1b, 0x30, 0xb8, 0x36, 0x2f,
	0xff, 0x0d, 0x8b, 0xbf, 0xf1, 0x29, 0x23, 0xc7, 0xe0, 0x68, 0xb7, 0x92, 0x21, 0x12, 0x16, 0xcc,
	0xeb, 0x6d, 0x96, 0xa2, 0xa8, 0xe7, 0x2d, 0x74, 0x33, 0x83, 0x92, 0xed, 0x3c, 0xa7, 0x60, 0x59,
	0xcf, 0xad, 0x02, 0xb8, 0x5f, 0x1f, 0x2b, 0x1f, 0x09, 0xeb, 0xd8, 0xdc, 0xa2, 0xf6, 0xb1, 0x96,
	0x95, 0xc9, 0x18, 0x20, 0x77, 0x21, 0xb1, 0xe8, 0x8b, 0xc6, 0xf4, 0x76, 0x1e, 0x41, 0x90, 0xe2,
	0x0d, 0x74, 0x8c, 0xeb, 0xc8, 0x56, 0x9e, 0x66, 0xdb, 0xd0, 0xdb, 0xae, 0xc4, 0x73, 0xd9, 0xda,
	0x4b, 0x99, 0xec, 0x82, 0xb5, 0x32, 0xd9, 0x25, 0x83, 0x1e, 0x41, 0x4b, 0x4d, 0x99, 0x6c, 0xe4,
	0x78, 0x36, 0x73, 0x6f, 0x58, 0x0c, 0xe2, 0x9e, 0x4b, 0x58, 0xb5, 0x87, 0x48, 0x3c, 0xcc, 0x7a,
	0x64, 0xb2, 0xde, 0xee, 0xa3, 0x98, 0x26, 0x0a, 0x1c, 0x85, 0xbd, 0xf8, 0x13, 0x00, 0x00, 0xff,
	0xff, 0x3c, 0x25, 0x9b, 0x64, 0xfc, 0x07, 0x00, 0x00,
}
