// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/portfolio.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Bio struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Bio) Reset()         { *m = Bio{} }
func (m *Bio) String() string { return proto.CompactTextString(m) }
func (*Bio) ProtoMessage()    {}
func (*Bio) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7973498bfb7f266, []int{0}
}
func (m *Bio) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bio.Unmarshal(m, b)
}
func (m *Bio) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bio.Marshal(b, m, deterministic)
}
func (m *Bio) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bio.Merge(m, src)
}
func (m *Bio) XXX_Size() int {
	return xxx_messageInfo_Bio.Size(m)
}
func (m *Bio) XXX_DiscardUnknown() {
	xxx_messageInfo_Bio.DiscardUnknown(m)
}

var xxx_messageInfo_Bio proto.InternalMessageInfo

func (m *Bio) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Bio) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type Course struct {
	ID                   uint32   `protobuf:"varint,1,opt,name=ID,json=iD,proto3" json:"ID,omitempty"`
	Institution          string   `protobuf:"bytes,2,opt,name=institution,proto3" json:"institution,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Dates                string   `protobuf:"bytes,4,opt,name=dates,proto3" json:"dates,omitempty"`
	Name                 string   `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Course) Reset()         { *m = Course{} }
func (m *Course) String() string { return proto.CompactTextString(m) }
func (*Course) ProtoMessage()    {}
func (*Course) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7973498bfb7f266, []int{1}
}
func (m *Course) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Course.Unmarshal(m, b)
}
func (m *Course) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Course.Marshal(b, m, deterministic)
}
func (m *Course) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Course.Merge(m, src)
}
func (m *Course) XXX_Size() int {
	return xxx_messageInfo_Course.Size(m)
}
func (m *Course) XXX_DiscardUnknown() {
	xxx_messageInfo_Course.DiscardUnknown(m)
}

var xxx_messageInfo_Course proto.InternalMessageInfo

func (m *Course) GetID() uint32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Course) GetInstitution() string {
	if m != nil {
		return m.Institution
	}
	return ""
}

func (m *Course) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Course) GetDates() string {
	if m != nil {
		return m.Dates
	}
	return ""
}

func (m *Course) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Education struct {
	Courses              []*Course `protobuf:"bytes,1,rep,name=courses,proto3" json:"courses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Education) Reset()         { *m = Education{} }
func (m *Education) String() string { return proto.CompactTextString(m) }
func (*Education) ProtoMessage()    {}
func (*Education) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7973498bfb7f266, []int{2}
}
func (m *Education) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Education.Unmarshal(m, b)
}
func (m *Education) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Education.Marshal(b, m, deterministic)
}
func (m *Education) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Education.Merge(m, src)
}
func (m *Education) XXX_Size() int {
	return xxx_messageInfo_Education.Size(m)
}
func (m *Education) XXX_DiscardUnknown() {
	xxx_messageInfo_Education.DiscardUnknown(m)
}

var xxx_messageInfo_Education proto.InternalMessageInfo

func (m *Education) GetCourses() []*Course {
	if m != nil {
		return m.Courses
	}
	return nil
}

type Skill struct {
	ID                   uint32   `protobuf:"varint,1,opt,name=ID,json=iD,proto3" json:"ID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Rating               uint32   `protobuf:"varint,3,opt,name=rating,proto3" json:"rating,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Skill) Reset()         { *m = Skill{} }
func (m *Skill) String() string { return proto.CompactTextString(m) }
func (*Skill) ProtoMessage()    {}
func (*Skill) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7973498bfb7f266, []int{3}
}
func (m *Skill) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Skill.Unmarshal(m, b)
}
func (m *Skill) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Skill.Marshal(b, m, deterministic)
}
func (m *Skill) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Skill.Merge(m, src)
}
func (m *Skill) XXX_Size() int {
	return xxx_messageInfo_Skill.Size(m)
}
func (m *Skill) XXX_DiscardUnknown() {
	xxx_messageInfo_Skill.DiscardUnknown(m)
}

var xxx_messageInfo_Skill proto.InternalMessageInfo

func (m *Skill) GetID() uint32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Skill) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Skill) GetRating() uint32 {
	if m != nil {
		return m.Rating
	}
	return 0
}

func (m *Skill) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type Skills struct {
	Skills               []*Skill `protobuf:"bytes,1,rep,name=skills,proto3" json:"skills,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Skills) Reset()         { *m = Skills{} }
func (m *Skills) String() string { return proto.CompactTextString(m) }
func (*Skills) ProtoMessage()    {}
func (*Skills) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7973498bfb7f266, []int{4}
}
func (m *Skills) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Skills.Unmarshal(m, b)
}
func (m *Skills) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Skills.Marshal(b, m, deterministic)
}
func (m *Skills) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Skills.Merge(m, src)
}
func (m *Skills) XXX_Size() int {
	return xxx_messageInfo_Skills.Size(m)
}
func (m *Skills) XXX_DiscardUnknown() {
	xxx_messageInfo_Skills.DiscardUnknown(m)
}

var xxx_messageInfo_Skills proto.InternalMessageInfo

func (m *Skills) GetSkills() []*Skill {
	if m != nil {
		return m.Skills
	}
	return nil
}

type Project struct {
	ID                   uint32   `protobuf:"varint,1,opt,name=ID,json=iD,proto3" json:"ID,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Meta                 string   `protobuf:"bytes,3,opt,name=meta,proto3" json:"meta,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Repo                 string   `protobuf:"bytes,5,opt,name=repo,proto3" json:"repo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Project) Reset()         { *m = Project{} }
func (m *Project) String() string { return proto.CompactTextString(m) }
func (*Project) ProtoMessage()    {}
func (*Project) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7973498bfb7f266, []int{5}
}
func (m *Project) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Project.Unmarshal(m, b)
}
func (m *Project) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Project.Marshal(b, m, deterministic)
}
func (m *Project) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Project.Merge(m, src)
}
func (m *Project) XXX_Size() int {
	return xxx_messageInfo_Project.Size(m)
}
func (m *Project) XXX_DiscardUnknown() {
	xxx_messageInfo_Project.DiscardUnknown(m)
}

var xxx_messageInfo_Project proto.InternalMessageInfo

func (m *Project) GetID() uint32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Project) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Project) GetMeta() string {
	if m != nil {
		return m.Meta
	}
	return ""
}

func (m *Project) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Project) GetRepo() string {
	if m != nil {
		return m.Repo
	}
	return ""
}

type Projects struct {
	Projects             []*Project `protobuf:"bytes,1,rep,name=projects,proto3" json:"projects,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Projects) Reset()         { *m = Projects{} }
func (m *Projects) String() string { return proto.CompactTextString(m) }
func (*Projects) ProtoMessage()    {}
func (*Projects) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7973498bfb7f266, []int{6}
}
func (m *Projects) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Projects.Unmarshal(m, b)
}
func (m *Projects) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Projects.Marshal(b, m, deterministic)
}
func (m *Projects) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Projects.Merge(m, src)
}
func (m *Projects) XXX_Size() int {
	return xxx_messageInfo_Projects.Size(m)
}
func (m *Projects) XXX_DiscardUnknown() {
	xxx_messageInfo_Projects.DiscardUnknown(m)
}

var xxx_messageInfo_Projects proto.InternalMessageInfo

func (m *Projects) GetProjects() []*Project {
	if m != nil {
		return m.Projects
	}
	return nil
}

type Job struct {
	ID                   uint32   `protobuf:"varint,1,opt,name=ID,json=iD,proto3" json:"ID,omitempty"`
	Company              string   `protobuf:"bytes,2,opt,name=company,proto3" json:"company,omitempty"`
	JobTitle             string   `protobuf:"bytes,3,opt,name=job_title,json=jobTitle,proto3" json:"job_title,omitempty"`
	Location             string   `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	Dates                string   `protobuf:"bytes,5,opt,name=dates,proto3" json:"dates,omitempty"`
	Description          string   `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	LogoUrl              string   `protobuf:"bytes,7,opt,name=logo_url,json=logoUrl,proto3" json:"logo_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Job) Reset()         { *m = Job{} }
func (m *Job) String() string { return proto.CompactTextString(m) }
func (*Job) ProtoMessage()    {}
func (*Job) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7973498bfb7f266, []int{7}
}
func (m *Job) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Job.Unmarshal(m, b)
}
func (m *Job) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Job.Marshal(b, m, deterministic)
}
func (m *Job) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Job.Merge(m, src)
}
func (m *Job) XXX_Size() int {
	return xxx_messageInfo_Job.Size(m)
}
func (m *Job) XXX_DiscardUnknown() {
	xxx_messageInfo_Job.DiscardUnknown(m)
}

var xxx_messageInfo_Job proto.InternalMessageInfo

func (m *Job) GetID() uint32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Job) GetCompany() string {
	if m != nil {
		return m.Company
	}
	return ""
}

func (m *Job) GetJobTitle() string {
	if m != nil {
		return m.JobTitle
	}
	return ""
}

func (m *Job) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *Job) GetDates() string {
	if m != nil {
		return m.Dates
	}
	return ""
}

func (m *Job) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Job) GetLogoUrl() string {
	if m != nil {
		return m.LogoUrl
	}
	return ""
}

type Experience struct {
	Jobs                 []*Job   `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Experience) Reset()         { *m = Experience{} }
func (m *Experience) String() string { return proto.CompactTextString(m) }
func (*Experience) ProtoMessage()    {}
func (*Experience) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7973498bfb7f266, []int{8}
}
func (m *Experience) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Experience.Unmarshal(m, b)
}
func (m *Experience) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Experience.Marshal(b, m, deterministic)
}
func (m *Experience) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Experience.Merge(m, src)
}
func (m *Experience) XXX_Size() int {
	return xxx_messageInfo_Experience.Size(m)
}
func (m *Experience) XXX_DiscardUnknown() {
	xxx_messageInfo_Experience.DiscardUnknown(m)
}

var xxx_messageInfo_Experience proto.InternalMessageInfo

func (m *Experience) GetJobs() []*Job {
	if m != nil {
		return m.Jobs
	}
	return nil
}

type CV struct {
	Bio                  *Bio        `protobuf:"bytes,1,opt,name=bio,proto3" json:"bio,omitempty"`
	Courses              *Education  `protobuf:"bytes,2,opt,name=courses,proto3" json:"courses,omitempty"`
	Jobs                 *Experience `protobuf:"bytes,3,opt,name=jobs,proto3" json:"jobs,omitempty"`
	Projects             *Projects   `protobuf:"bytes,4,opt,name=projects,proto3" json:"projects,omitempty"`
	Skills               *Skills     `protobuf:"bytes,5,opt,name=skills,proto3" json:"skills,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CV) Reset()         { *m = CV{} }
func (m *CV) String() string { return proto.CompactTextString(m) }
func (*CV) ProtoMessage()    {}
func (*CV) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7973498bfb7f266, []int{9}
}
func (m *CV) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CV.Unmarshal(m, b)
}
func (m *CV) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CV.Marshal(b, m, deterministic)
}
func (m *CV) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CV.Merge(m, src)
}
func (m *CV) XXX_Size() int {
	return xxx_messageInfo_CV.Size(m)
}
func (m *CV) XXX_DiscardUnknown() {
	xxx_messageInfo_CV.DiscardUnknown(m)
}

var xxx_messageInfo_CV proto.InternalMessageInfo

func (m *CV) GetBio() *Bio {
	if m != nil {
		return m.Bio
	}
	return nil
}

func (m *CV) GetCourses() *Education {
	if m != nil {
		return m.Courses
	}
	return nil
}

func (m *CV) GetJobs() *Experience {
	if m != nil {
		return m.Jobs
	}
	return nil
}

func (m *CV) GetProjects() *Projects {
	if m != nil {
		return m.Projects
	}
	return nil
}

func (m *CV) GetSkills() *Skills {
	if m != nil {
		return m.Skills
	}
	return nil
}

type ContactForm struct {
	First                string   `protobuf:"bytes,1,opt,name=first,proto3" json:"first,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Last                 string   `protobuf:"bytes,3,opt,name=last,proto3" json:"last,omitempty"`
	Mobile               string   `protobuf:"bytes,4,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Text                 string   `protobuf:"bytes,5,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContactForm) Reset()         { *m = ContactForm{} }
func (m *ContactForm) String() string { return proto.CompactTextString(m) }
func (*ContactForm) ProtoMessage()    {}
func (*ContactForm) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7973498bfb7f266, []int{10}
}
func (m *ContactForm) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContactForm.Unmarshal(m, b)
}
func (m *ContactForm) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContactForm.Marshal(b, m, deterministic)
}
func (m *ContactForm) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContactForm.Merge(m, src)
}
func (m *ContactForm) XXX_Size() int {
	return xxx_messageInfo_ContactForm.Size(m)
}
func (m *ContactForm) XXX_DiscardUnknown() {
	xxx_messageInfo_ContactForm.DiscardUnknown(m)
}

var xxx_messageInfo_ContactForm proto.InternalMessageInfo

func (m *ContactForm) GetFirst() string {
	if m != nil {
		return m.First
	}
	return ""
}

func (m *ContactForm) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *ContactForm) GetLast() string {
	if m != nil {
		return m.Last
	}
	return ""
}

func (m *ContactForm) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *ContactForm) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type FormConfirmation struct {
	Confirmed            bool     `protobuf:"varint,1,opt,name=confirmed,proto3" json:"confirmed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FormConfirmation) Reset()         { *m = FormConfirmation{} }
func (m *FormConfirmation) String() string { return proto.CompactTextString(m) }
func (*FormConfirmation) ProtoMessage()    {}
func (*FormConfirmation) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7973498bfb7f266, []int{11}
}
func (m *FormConfirmation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FormConfirmation.Unmarshal(m, b)
}
func (m *FormConfirmation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FormConfirmation.Marshal(b, m, deterministic)
}
func (m *FormConfirmation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FormConfirmation.Merge(m, src)
}
func (m *FormConfirmation) XXX_Size() int {
	return xxx_messageInfo_FormConfirmation.Size(m)
}
func (m *FormConfirmation) XXX_DiscardUnknown() {
	xxx_messageInfo_FormConfirmation.DiscardUnknown(m)
}

var xxx_messageInfo_FormConfirmation proto.InternalMessageInfo

func (m *FormConfirmation) GetConfirmed() bool {
	if m != nil {
		return m.Confirmed
	}
	return false
}

type GetCVResponse struct {
	Cv                   *CV      `protobuf:"bytes,1,opt,name=cv,proto3" json:"cv,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCVResponse) Reset()         { *m = GetCVResponse{} }
func (m *GetCVResponse) String() string { return proto.CompactTextString(m) }
func (*GetCVResponse) ProtoMessage()    {}
func (*GetCVResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7973498bfb7f266, []int{12}
}
func (m *GetCVResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCVResponse.Unmarshal(m, b)
}
func (m *GetCVResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCVResponse.Marshal(b, m, deterministic)
}
func (m *GetCVResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCVResponse.Merge(m, src)
}
func (m *GetCVResponse) XXX_Size() int {
	return xxx_messageInfo_GetCVResponse.Size(m)
}
func (m *GetCVResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCVResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCVResponse proto.InternalMessageInfo

func (m *GetCVResponse) GetCv() *CV {
	if m != nil {
		return m.Cv
	}
	return nil
}

type GetCVRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCVRequest) Reset()         { *m = GetCVRequest{} }
func (m *GetCVRequest) String() string { return proto.CompactTextString(m) }
func (*GetCVRequest) ProtoMessage()    {}
func (*GetCVRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7973498bfb7f266, []int{13}
}
func (m *GetCVRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCVRequest.Unmarshal(m, b)
}
func (m *GetCVRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCVRequest.Marshal(b, m, deterministic)
}
func (m *GetCVRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCVRequest.Merge(m, src)
}
func (m *GetCVRequest) XXX_Size() int {
	return xxx_messageInfo_GetCVRequest.Size(m)
}
func (m *GetCVRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCVRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCVRequest proto.InternalMessageInfo

type ContactResponse struct {
	FormAccepted         *FormConfirmation `protobuf:"bytes,1,opt,name=formAccepted,proto3" json:"formAccepted,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ContactResponse) Reset()         { *m = ContactResponse{} }
func (m *ContactResponse) String() string { return proto.CompactTextString(m) }
func (*ContactResponse) ProtoMessage()    {}
func (*ContactResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7973498bfb7f266, []int{14}
}
func (m *ContactResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContactResponse.Unmarshal(m, b)
}
func (m *ContactResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContactResponse.Marshal(b, m, deterministic)
}
func (m *ContactResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContactResponse.Merge(m, src)
}
func (m *ContactResponse) XXX_Size() int {
	return xxx_messageInfo_ContactResponse.Size(m)
}
func (m *ContactResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ContactResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ContactResponse proto.InternalMessageInfo

func (m *ContactResponse) GetFormAccepted() *FormConfirmation {
	if m != nil {
		return m.FormAccepted
	}
	return nil
}

type ContactRequest struct {
	Form                 *ContactForm `protobuf:"bytes,1,opt,name=form,proto3" json:"form,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ContactRequest) Reset()         { *m = ContactRequest{} }
func (m *ContactRequest) String() string { return proto.CompactTextString(m) }
func (*ContactRequest) ProtoMessage()    {}
func (*ContactRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7973498bfb7f266, []int{15}
}
func (m *ContactRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContactRequest.Unmarshal(m, b)
}
func (m *ContactRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContactRequest.Marshal(b, m, deterministic)
}
func (m *ContactRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContactRequest.Merge(m, src)
}
func (m *ContactRequest) XXX_Size() int {
	return xxx_messageInfo_ContactRequest.Size(m)
}
func (m *ContactRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ContactRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ContactRequest proto.InternalMessageInfo

func (m *ContactRequest) GetForm() *ContactForm {
	if m != nil {
		return m.Form
	}
	return nil
}

func init() {
	proto.RegisterType((*Bio)(nil), "proto.Bio")
	proto.RegisterType((*Course)(nil), "proto.Course")
	proto.RegisterType((*Education)(nil), "proto.Education")
	proto.RegisterType((*Skill)(nil), "proto.Skill")
	proto.RegisterType((*Skills)(nil), "proto.Skills")
	proto.RegisterType((*Project)(nil), "proto.Project")
	proto.RegisterType((*Projects)(nil), "proto.Projects")
	proto.RegisterType((*Job)(nil), "proto.Job")
	proto.RegisterType((*Experience)(nil), "proto.Experience")
	proto.RegisterType((*CV)(nil), "proto.CV")
	proto.RegisterType((*ContactForm)(nil), "proto.ContactForm")
	proto.RegisterType((*FormConfirmation)(nil), "proto.FormConfirmation")
	proto.RegisterType((*GetCVResponse)(nil), "proto.GetCVResponse")
	proto.RegisterType((*GetCVRequest)(nil), "proto.GetCVRequest")
	proto.RegisterType((*ContactResponse)(nil), "proto.ContactResponse")
	proto.RegisterType((*ContactRequest)(nil), "proto.ContactRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PortfolioServiceClient is the client API for PortfolioService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PortfolioServiceClient interface {
	GetCV(ctx context.Context, in *GetCVRequest, opts ...grpc.CallOption) (PortfolioService_GetCVClient, error)
	Contact(ctx context.Context, in *ContactRequest, opts ...grpc.CallOption) (PortfolioService_ContactClient, error)
}

type portfolioServiceClient struct {
	cc *grpc.ClientConn
}

func NewPortfolioServiceClient(cc *grpc.ClientConn) PortfolioServiceClient {
	return &portfolioServiceClient{cc}
}

func (c *portfolioServiceClient) GetCV(ctx context.Context, in *GetCVRequest, opts ...grpc.CallOption) (PortfolioService_GetCVClient, error) {
	stream, err := c.cc.NewStream(ctx, &_PortfolioService_serviceDesc.Streams[0], "/proto.PortfolioService/GetCV", opts...)
	if err != nil {
		return nil, err
	}
	x := &portfolioServiceGetCVClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PortfolioService_GetCVClient interface {
	Recv() (*GetCVResponse, error)
	grpc.ClientStream
}

type portfolioServiceGetCVClient struct {
	grpc.ClientStream
}

func (x *portfolioServiceGetCVClient) Recv() (*GetCVResponse, error) {
	m := new(GetCVResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *portfolioServiceClient) Contact(ctx context.Context, in *ContactRequest, opts ...grpc.CallOption) (PortfolioService_ContactClient, error) {
	stream, err := c.cc.NewStream(ctx, &_PortfolioService_serviceDesc.Streams[1], "/proto.PortfolioService/Contact", opts...)
	if err != nil {
		return nil, err
	}
	x := &portfolioServiceContactClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PortfolioService_ContactClient interface {
	Recv() (*ContactResponse, error)
	grpc.ClientStream
}

type portfolioServiceContactClient struct {
	grpc.ClientStream
}

func (x *portfolioServiceContactClient) Recv() (*ContactResponse, error) {
	m := new(ContactResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PortfolioServiceServer is the server API for PortfolioService service.
type PortfolioServiceServer interface {
	GetCV(*GetCVRequest, PortfolioService_GetCVServer) error
	Contact(*ContactRequest, PortfolioService_ContactServer) error
}

func RegisterPortfolioServiceServer(s *grpc.Server, srv PortfolioServiceServer) {
	s.RegisterService(&_PortfolioService_serviceDesc, srv)
}

func _PortfolioService_GetCV_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetCVRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PortfolioServiceServer).GetCV(m, &portfolioServiceGetCVServer{stream})
}

type PortfolioService_GetCVServer interface {
	Send(*GetCVResponse) error
	grpc.ServerStream
}

type portfolioServiceGetCVServer struct {
	grpc.ServerStream
}

func (x *portfolioServiceGetCVServer) Send(m *GetCVResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _PortfolioService_Contact_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ContactRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PortfolioServiceServer).Contact(m, &portfolioServiceContactServer{stream})
}

type PortfolioService_ContactServer interface {
	Send(*ContactResponse) error
	grpc.ServerStream
}

type portfolioServiceContactServer struct {
	grpc.ServerStream
}

func (x *portfolioServiceContactServer) Send(m *ContactResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _PortfolioService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.PortfolioService",
	HandlerType: (*PortfolioServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetCV",
			Handler:       _PortfolioService_GetCV_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Contact",
			Handler:       _PortfolioService_Contact_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/portfolio.proto",
}

func init() { proto.RegisterFile("proto/portfolio.proto", fileDescriptor_d7973498bfb7f266) }

var fileDescriptor_d7973498bfb7f266 = []byte{
	// 702 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x54, 0xdd, 0x4e, 0xdb, 0x4a,
	0x10, 0x96, 0x9d, 0xff, 0x09, 0x09, 0x9c, 0x3d, 0xc0, 0x09, 0x1c, 0x54, 0xa1, 0x55, 0x69, 0x11,
	0xad, 0x28, 0xa2, 0xa8, 0xaa, 0x5a, 0xf5, 0xa2, 0x04, 0x5a, 0x95, 0x8b, 0x0a, 0x99, 0x96, 0x5b,
	0x64, 0x3b, 0x1b, 0xb4, 0xa9, 0xed, 0x75, 0x77, 0x37, 0x08, 0xee, 0xab, 0xbe, 0x54, 0x9f, 0xa0,
	0x6f, 0x55, 0xed, 0x78, 0xd7, 0x71, 0x92, 0x8b, 0x5e, 0x65, 0x7e, 0xbe, 0x99, 0xf9, 0x66, 0xe7,
	0x8b, 0x61, 0x23, 0x97, 0x42, 0x8b, 0x17, 0xb9, 0x90, 0x7a, 0x2c, 0x12, 0x2e, 0x0e, 0xd1, 0x27,
	0x0d, 0xfc, 0xa1, 0xef, 0xa0, 0x76, 0xca, 0x05, 0x59, 0x87, 0x86, 0xe6, 0x3a, 0x61, 0x03, 0x6f,
	0xd7, 0xdb, 0xef, 0x04, 0x85, 0x43, 0x76, 0xa1, 0x3b, 0x62, 0x2a, 0x96, 0x3c, 0xd7, 0x5c, 0x64,
	0x03, 0x1f, 0x73, 0xd5, 0x10, 0xfd, 0xe9, 0x41, 0x73, 0x28, 0xa6, 0x52, 0x31, 0xd2, 0x07, 0xff,
	0xd3, 0x19, 0xd6, 0xf7, 0x02, 0x9f, 0x9f, 0x99, 0x62, 0x9e, 0x29, 0xcd, 0xf5, 0xb4, 0x5a, 0x5c,
	0x09, 0x2d, 0xb6, 0xaf, 0x2d, 0xb5, 0x37, 0xb4, 0x46, 0xa1, 0x66, 0x6a, 0x50, 0x2f, 0x68, 0xa1,
	0x43, 0x08, 0xd4, 0xb3, 0x30, 0x65, 0x83, 0x06, 0x06, 0xd1, 0xa6, 0x27, 0xd0, 0x39, 0x1f, 0x4d,
	0xe3, 0x10, 0xcb, 0x9e, 0x42, 0x2b, 0x46, 0x52, 0x6a, 0xe0, 0xed, 0xd6, 0xf6, 0xbb, 0xc7, 0xbd,
	0x62, 0xe9, 0xc3, 0x82, 0x6a, 0xe0, 0xb2, 0x94, 0x41, 0xe3, 0xea, 0x1b, 0x4f, 0x92, 0x25, 0xf2,
	0x6e, 0x84, 0x3f, 0x1b, 0x41, 0x36, 0xa1, 0x29, 0x43, 0xcd, 0xb3, 0x5b, 0x64, 0xda, 0x0b, 0xac,
	0xb7, 0xb8, 0x46, 0x7d, 0xf9, 0x95, 0x0e, 0xa1, 0x89, 0x63, 0x14, 0x79, 0x0c, 0x4d, 0x85, 0x96,
	0x25, 0xb6, 0x62, 0x89, 0x61, 0x3a, 0xb0, 0x39, 0xfa, 0x00, 0xad, 0x4b, 0x29, 0x26, 0x2c, 0xd6,
	0x4b, 0xc4, 0xca, 0x43, 0xf9, 0xd5, 0x43, 0x11, 0xa8, 0xa7, 0x4c, 0x87, 0xf6, 0x09, 0xd1, 0xfe,
	0x3b, 0x2d, 0x53, 0x25, 0x59, 0x2e, 0xdc, 0x3b, 0x1a, 0x9b, 0xbe, 0x82, 0xb6, 0x1d, 0xad, 0xc8,
	0x01, 0xb4, 0x73, 0x6b, 0x5b, 0xba, 0x7d, 0x4b, 0xd7, 0x42, 0x82, 0x32, 0x4f, 0x7f, 0x79, 0x50,
	0xbb, 0x10, 0xd1, 0x12, 0xdf, 0x81, 0x39, 0x45, 0x9a, 0x87, 0xd9, 0x83, 0x65, 0xec, 0x5c, 0xf2,
	0x3f, 0x74, 0x26, 0x22, 0xba, 0x29, 0xb6, 0x29, 0x88, 0xb7, 0x27, 0x22, 0xfa, 0x82, 0x0b, 0x6d,
	0x43, 0x3b, 0x11, 0xc5, 0x35, 0x2d, 0xf3, 0xd2, 0x9f, 0x89, 0xa2, 0x51, 0x15, 0xc5, 0xc2, 0xba,
	0xcd, 0xe5, 0x75, 0xb7, 0x4c, 0xcf, 0x5b, 0x71, 0x33, 0x95, 0xc9, 0xa0, 0x55, 0x70, 0x31, 0xfe,
	0x57, 0x99, 0xd0, 0xe7, 0x00, 0xe7, 0xf7, 0x39, 0x93, 0x9c, 0x65, 0x31, 0x23, 0x8f, 0xa0, 0x3e,
	0x11, 0x91, 0xdb, 0x19, 0xec, 0xce, 0x17, 0x22, 0x0a, 0x30, 0x4e, 0x7f, 0x7b, 0xe0, 0x0f, 0xaf,
	0xc9, 0x0e, 0xd4, 0x22, 0x2e, 0x70, 0xd7, 0x19, 0xea, 0x94, 0x8b, 0xc0, 0x84, 0xc9, 0xc1, 0x4c,
	0x83, 0x3e, 0x22, 0xd6, 0x2c, 0xa2, 0x94, 0x69, 0x29, 0x43, 0xb2, 0x67, 0x07, 0xd6, 0x10, 0xf8,
	0x8f, 0x03, 0x96, 0x8c, 0x8a, 0xb9, 0xe4, 0x59, 0xe5, 0x1e, 0x75, 0x84, 0xae, 0xce, 0xdf, 0x43,
	0xcd, 0x0e, 0x42, 0xf6, 0x4a, 0xa5, 0x35, 0x10, 0xda, 0xab, 0x2a, 0x4d, 0x55, 0xa4, 0xd6, 0x1d,
	0x8a, 0x4c, 0x87, 0xb1, 0xfe, 0x20, 0x64, 0x6a, 0xde, 0x76, 0xcc, 0xa5, 0xd2, 0xee, 0x3b, 0x80,
	0x8e, 0x89, 0xb2, 0x34, 0xe4, 0x89, 0x13, 0x1d, 0x3a, 0x46, 0x3e, 0x49, 0xa8, 0xb4, 0x13, 0x9d,
	0xb1, 0xcd, 0x7f, 0x24, 0x15, 0x11, 0x4f, 0x98, 0xbd, 0x9a, 0xf5, 0x0c, 0x56, 0xb3, 0x7b, 0xed,
	0xa4, 0x66, 0x6c, 0x7a, 0x04, 0x6b, 0x66, 0xe6, 0x50, 0x64, 0x63, 0x2e, 0xd3, 0xe2, 0xb6, 0x3b,
	0xd0, 0x89, 0x0b, 0x9f, 0x8d, 0x90, 0x43, 0x3b, 0x98, 0x05, 0xe8, 0x01, 0xf4, 0x3e, 0x32, 0x3d,
	0xbc, 0x0e, 0x98, 0xca, 0x45, 0xa6, 0x18, 0xd9, 0x02, 0x3f, 0xbe, 0xb3, 0x17, 0xe8, 0xb8, 0xff,
	0xf8, 0x75, 0xe0, 0xc7, 0x77, 0xb4, 0x0f, 0x2b, 0x16, 0xfb, 0x7d, 0xca, 0x94, 0xa6, 0x9f, 0x61,
	0xd5, 0x2e, 0x5a, 0x56, 0xbf, 0x85, 0x95, 0xb1, 0x90, 0xe9, 0xfb, 0x38, 0x66, 0xb9, 0xb6, 0xf3,
	0xba, 0xc7, 0xff, 0xd9, 0x3e, 0x8b, 0xdc, 0x82, 0x39, 0x30, 0x7d, 0x0d, 0xfd, 0xb2, 0x1f, 0x4e,
	0x20, 0x4f, 0xa0, 0x6e, 0x10, 0xb6, 0x0d, 0x29, 0x3f, 0x39, 0xe5, 0xeb, 0x06, 0x98, 0x3f, 0xfe,
	0xe1, 0xc1, 0xda, 0xa5, 0xfb, 0x1a, 0x5f, 0x31, 0x79, 0xc7, 0x63, 0x46, 0x4e, 0xa0, 0x81, 0x74,
	0xc9, 0xbf, 0xb6, 0xae, 0x4a, 0x7e, 0x7b, 0x7d, 0x3e, 0x58, 0xf0, 0x3f, 0xf2, 0xc8, 0x1b, 0x68,
	0xd9, 0xfe, 0x64, 0x63, 0x7e, 0x9e, 0xab, 0xdc, 0x5c, 0x0c, 0xbb, 0xda, 0xa8, 0x89, 0x89, 0x97,
	0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0xca, 0xa4, 0xec, 0xb6, 0x20, 0x06, 0x00, 0x00,
}
