// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/portfolio.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Bio struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Bio) Reset()         { *m = Bio{} }
func (m *Bio) String() string { return proto.CompactTextString(m) }
func (*Bio) ProtoMessage()    {}
func (*Bio) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7973498bfb7f266, []int{0}
}
func (m *Bio) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bio.Unmarshal(m, b)
}
func (m *Bio) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bio.Marshal(b, m, deterministic)
}
func (m *Bio) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bio.Merge(m, src)
}
func (m *Bio) XXX_Size() int {
	return xxx_messageInfo_Bio.Size(m)
}
func (m *Bio) XXX_DiscardUnknown() {
	xxx_messageInfo_Bio.DiscardUnknown(m)
}

var xxx_messageInfo_Bio proto.InternalMessageInfo

func (m *Bio) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Bio) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type Course struct {
	ID                   uint32   `protobuf:"varint,1,opt,name=ID,json=iD,proto3" json:"ID,omitempty"`
	Institution          string   `protobuf:"bytes,2,opt,name=institution,proto3" json:"institution,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Dates                string   `protobuf:"bytes,4,opt,name=dates,proto3" json:"dates,omitempty"`
	Name                 string   `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Course) Reset()         { *m = Course{} }
func (m *Course) String() string { return proto.CompactTextString(m) }
func (*Course) ProtoMessage()    {}
func (*Course) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7973498bfb7f266, []int{1}
}
func (m *Course) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Course.Unmarshal(m, b)
}
func (m *Course) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Course.Marshal(b, m, deterministic)
}
func (m *Course) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Course.Merge(m, src)
}
func (m *Course) XXX_Size() int {
	return xxx_messageInfo_Course.Size(m)
}
func (m *Course) XXX_DiscardUnknown() {
	xxx_messageInfo_Course.DiscardUnknown(m)
}

var xxx_messageInfo_Course proto.InternalMessageInfo

func (m *Course) GetID() uint32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Course) GetInstitution() string {
	if m != nil {
		return m.Institution
	}
	return ""
}

func (m *Course) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Course) GetDates() string {
	if m != nil {
		return m.Dates
	}
	return ""
}

func (m *Course) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Education struct {
	Courses              []*Course `protobuf:"bytes,1,rep,name=courses,proto3" json:"courses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Education) Reset()         { *m = Education{} }
func (m *Education) String() string { return proto.CompactTextString(m) }
func (*Education) ProtoMessage()    {}
func (*Education) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7973498bfb7f266, []int{2}
}
func (m *Education) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Education.Unmarshal(m, b)
}
func (m *Education) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Education.Marshal(b, m, deterministic)
}
func (m *Education) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Education.Merge(m, src)
}
func (m *Education) XXX_Size() int {
	return xxx_messageInfo_Education.Size(m)
}
func (m *Education) XXX_DiscardUnknown() {
	xxx_messageInfo_Education.DiscardUnknown(m)
}

var xxx_messageInfo_Education proto.InternalMessageInfo

func (m *Education) GetCourses() []*Course {
	if m != nil {
		return m.Courses
	}
	return nil
}

type Skill struct {
	ID                   uint32   `protobuf:"varint,1,opt,name=ID,json=iD,proto3" json:"ID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Rating               uint32   `protobuf:"varint,3,opt,name=rating,proto3" json:"rating,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Skill) Reset()         { *m = Skill{} }
func (m *Skill) String() string { return proto.CompactTextString(m) }
func (*Skill) ProtoMessage()    {}
func (*Skill) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7973498bfb7f266, []int{3}
}
func (m *Skill) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Skill.Unmarshal(m, b)
}
func (m *Skill) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Skill.Marshal(b, m, deterministic)
}
func (m *Skill) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Skill.Merge(m, src)
}
func (m *Skill) XXX_Size() int {
	return xxx_messageInfo_Skill.Size(m)
}
func (m *Skill) XXX_DiscardUnknown() {
	xxx_messageInfo_Skill.DiscardUnknown(m)
}

var xxx_messageInfo_Skill proto.InternalMessageInfo

func (m *Skill) GetID() uint32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Skill) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Skill) GetRating() uint32 {
	if m != nil {
		return m.Rating
	}
	return 0
}

func (m *Skill) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type Skills struct {
	Skills               []*Skill `protobuf:"bytes,1,rep,name=skills,proto3" json:"skills,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Skills) Reset()         { *m = Skills{} }
func (m *Skills) String() string { return proto.CompactTextString(m) }
func (*Skills) ProtoMessage()    {}
func (*Skills) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7973498bfb7f266, []int{4}
}
func (m *Skills) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Skills.Unmarshal(m, b)
}
func (m *Skills) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Skills.Marshal(b, m, deterministic)
}
func (m *Skills) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Skills.Merge(m, src)
}
func (m *Skills) XXX_Size() int {
	return xxx_messageInfo_Skills.Size(m)
}
func (m *Skills) XXX_DiscardUnknown() {
	xxx_messageInfo_Skills.DiscardUnknown(m)
}

var xxx_messageInfo_Skills proto.InternalMessageInfo

func (m *Skills) GetSkills() []*Skill {
	if m != nil {
		return m.Skills
	}
	return nil
}

type Project struct {
	ID                   uint32   `protobuf:"varint,1,opt,name=ID,json=iD,proto3" json:"ID,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Meta                 string   `protobuf:"bytes,3,opt,name=meta,proto3" json:"meta,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Project) Reset()         { *m = Project{} }
func (m *Project) String() string { return proto.CompactTextString(m) }
func (*Project) ProtoMessage()    {}
func (*Project) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7973498bfb7f266, []int{5}
}
func (m *Project) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Project.Unmarshal(m, b)
}
func (m *Project) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Project.Marshal(b, m, deterministic)
}
func (m *Project) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Project.Merge(m, src)
}
func (m *Project) XXX_Size() int {
	return xxx_messageInfo_Project.Size(m)
}
func (m *Project) XXX_DiscardUnknown() {
	xxx_messageInfo_Project.DiscardUnknown(m)
}

var xxx_messageInfo_Project proto.InternalMessageInfo

func (m *Project) GetID() uint32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Project) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Project) GetMeta() string {
	if m != nil {
		return m.Meta
	}
	return ""
}

func (m *Project) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type Projects struct {
	Projects             []*Project `protobuf:"bytes,1,rep,name=projects,proto3" json:"projects,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Projects) Reset()         { *m = Projects{} }
func (m *Projects) String() string { return proto.CompactTextString(m) }
func (*Projects) ProtoMessage()    {}
func (*Projects) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7973498bfb7f266, []int{6}
}
func (m *Projects) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Projects.Unmarshal(m, b)
}
func (m *Projects) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Projects.Marshal(b, m, deterministic)
}
func (m *Projects) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Projects.Merge(m, src)
}
func (m *Projects) XXX_Size() int {
	return xxx_messageInfo_Projects.Size(m)
}
func (m *Projects) XXX_DiscardUnknown() {
	xxx_messageInfo_Projects.DiscardUnknown(m)
}

var xxx_messageInfo_Projects proto.InternalMessageInfo

func (m *Projects) GetProjects() []*Project {
	if m != nil {
		return m.Projects
	}
	return nil
}

type Job struct {
	ID                   uint32   `protobuf:"varint,1,opt,name=ID,json=iD,proto3" json:"ID,omitempty"`
	Company              string   `protobuf:"bytes,2,opt,name=company,proto3" json:"company,omitempty"`
	JobTitle             string   `protobuf:"bytes,3,opt,name=job_title,json=jobTitle,proto3" json:"job_title,omitempty"`
	Location             string   `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	Dates                string   `protobuf:"bytes,5,opt,name=dates,proto3" json:"dates,omitempty"`
	Description          string   `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	LogoUrl              string   `protobuf:"bytes,7,opt,name=logo_url,json=logoUrl,proto3" json:"logo_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Job) Reset()         { *m = Job{} }
func (m *Job) String() string { return proto.CompactTextString(m) }
func (*Job) ProtoMessage()    {}
func (*Job) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7973498bfb7f266, []int{7}
}
func (m *Job) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Job.Unmarshal(m, b)
}
func (m *Job) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Job.Marshal(b, m, deterministic)
}
func (m *Job) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Job.Merge(m, src)
}
func (m *Job) XXX_Size() int {
	return xxx_messageInfo_Job.Size(m)
}
func (m *Job) XXX_DiscardUnknown() {
	xxx_messageInfo_Job.DiscardUnknown(m)
}

var xxx_messageInfo_Job proto.InternalMessageInfo

func (m *Job) GetID() uint32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Job) GetCompany() string {
	if m != nil {
		return m.Company
	}
	return ""
}

func (m *Job) GetJobTitle() string {
	if m != nil {
		return m.JobTitle
	}
	return ""
}

func (m *Job) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *Job) GetDates() string {
	if m != nil {
		return m.Dates
	}
	return ""
}

func (m *Job) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Job) GetLogoUrl() string {
	if m != nil {
		return m.LogoUrl
	}
	return ""
}

type Experience struct {
	Jobs                 []*Job   `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Experience) Reset()         { *m = Experience{} }
func (m *Experience) String() string { return proto.CompactTextString(m) }
func (*Experience) ProtoMessage()    {}
func (*Experience) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7973498bfb7f266, []int{8}
}
func (m *Experience) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Experience.Unmarshal(m, b)
}
func (m *Experience) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Experience.Marshal(b, m, deterministic)
}
func (m *Experience) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Experience.Merge(m, src)
}
func (m *Experience) XXX_Size() int {
	return xxx_messageInfo_Experience.Size(m)
}
func (m *Experience) XXX_DiscardUnknown() {
	xxx_messageInfo_Experience.DiscardUnknown(m)
}

var xxx_messageInfo_Experience proto.InternalMessageInfo

func (m *Experience) GetJobs() []*Job {
	if m != nil {
		return m.Jobs
	}
	return nil
}

type AddBioResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddBioResponse) Reset()         { *m = AddBioResponse{} }
func (m *AddBioResponse) String() string { return proto.CompactTextString(m) }
func (*AddBioResponse) ProtoMessage()    {}
func (*AddBioResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7973498bfb7f266, []int{9}
}
func (m *AddBioResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddBioResponse.Unmarshal(m, b)
}
func (m *AddBioResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddBioResponse.Marshal(b, m, deterministic)
}
func (m *AddBioResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddBioResponse.Merge(m, src)
}
func (m *AddBioResponse) XXX_Size() int {
	return xxx_messageInfo_AddBioResponse.Size(m)
}
func (m *AddBioResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddBioResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddBioResponse proto.InternalMessageInfo

type AddBioRequest struct {
	Bio                  *Bio     `protobuf:"bytes,1,opt,name=bio,proto3" json:"bio,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddBioRequest) Reset()         { *m = AddBioRequest{} }
func (m *AddBioRequest) String() string { return proto.CompactTextString(m) }
func (*AddBioRequest) ProtoMessage()    {}
func (*AddBioRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7973498bfb7f266, []int{10}
}
func (m *AddBioRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddBioRequest.Unmarshal(m, b)
}
func (m *AddBioRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddBioRequest.Marshal(b, m, deterministic)
}
func (m *AddBioRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddBioRequest.Merge(m, src)
}
func (m *AddBioRequest) XXX_Size() int {
	return xxx_messageInfo_AddBioRequest.Size(m)
}
func (m *AddBioRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddBioRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddBioRequest proto.InternalMessageInfo

func (m *AddBioRequest) GetBio() *Bio {
	if m != nil {
		return m.Bio
	}
	return nil
}

type AddCVResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddCVResponse) Reset()         { *m = AddCVResponse{} }
func (m *AddCVResponse) String() string { return proto.CompactTextString(m) }
func (*AddCVResponse) ProtoMessage()    {}
func (*AddCVResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7973498bfb7f266, []int{11}
}
func (m *AddCVResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddCVResponse.Unmarshal(m, b)
}
func (m *AddCVResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddCVResponse.Marshal(b, m, deterministic)
}
func (m *AddCVResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddCVResponse.Merge(m, src)
}
func (m *AddCVResponse) XXX_Size() int {
	return xxx_messageInfo_AddCVResponse.Size(m)
}
func (m *AddCVResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddCVResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddCVResponse proto.InternalMessageInfo

type AddCVRequest struct {
	Skills               *Skills     `protobuf:"bytes,1,opt,name=skills,proto3" json:"skills,omitempty"`
	Jobs                 *Experience `protobuf:"bytes,2,opt,name=jobs,proto3" json:"jobs,omitempty"`
	Courses              *Education  `protobuf:"bytes,3,opt,name=courses,proto3" json:"courses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *AddCVRequest) Reset()         { *m = AddCVRequest{} }
func (m *AddCVRequest) String() string { return proto.CompactTextString(m) }
func (*AddCVRequest) ProtoMessage()    {}
func (*AddCVRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7973498bfb7f266, []int{12}
}
func (m *AddCVRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddCVRequest.Unmarshal(m, b)
}
func (m *AddCVRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddCVRequest.Marshal(b, m, deterministic)
}
func (m *AddCVRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddCVRequest.Merge(m, src)
}
func (m *AddCVRequest) XXX_Size() int {
	return xxx_messageInfo_AddCVRequest.Size(m)
}
func (m *AddCVRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddCVRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddCVRequest proto.InternalMessageInfo

func (m *AddCVRequest) GetSkills() *Skills {
	if m != nil {
		return m.Skills
	}
	return nil
}

func (m *AddCVRequest) GetJobs() *Experience {
	if m != nil {
		return m.Jobs
	}
	return nil
}

func (m *AddCVRequest) GetCourses() *Education {
	if m != nil {
		return m.Courses
	}
	return nil
}

type AddProjectsResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddProjectsResponse) Reset()         { *m = AddProjectsResponse{} }
func (m *AddProjectsResponse) String() string { return proto.CompactTextString(m) }
func (*AddProjectsResponse) ProtoMessage()    {}
func (*AddProjectsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7973498bfb7f266, []int{13}
}
func (m *AddProjectsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddProjectsResponse.Unmarshal(m, b)
}
func (m *AddProjectsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddProjectsResponse.Marshal(b, m, deterministic)
}
func (m *AddProjectsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddProjectsResponse.Merge(m, src)
}
func (m *AddProjectsResponse) XXX_Size() int {
	return xxx_messageInfo_AddProjectsResponse.Size(m)
}
func (m *AddProjectsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddProjectsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddProjectsResponse proto.InternalMessageInfo

type AddProjectsRequest struct {
	Projects             *Projects `protobuf:"bytes,1,opt,name=projects,proto3" json:"projects,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AddProjectsRequest) Reset()         { *m = AddProjectsRequest{} }
func (m *AddProjectsRequest) String() string { return proto.CompactTextString(m) }
func (*AddProjectsRequest) ProtoMessage()    {}
func (*AddProjectsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7973498bfb7f266, []int{14}
}
func (m *AddProjectsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddProjectsRequest.Unmarshal(m, b)
}
func (m *AddProjectsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddProjectsRequest.Marshal(b, m, deterministic)
}
func (m *AddProjectsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddProjectsRequest.Merge(m, src)
}
func (m *AddProjectsRequest) XXX_Size() int {
	return xxx_messageInfo_AddProjectsRequest.Size(m)
}
func (m *AddProjectsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddProjectsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddProjectsRequest proto.InternalMessageInfo

func (m *AddProjectsRequest) GetProjects() *Projects {
	if m != nil {
		return m.Projects
	}
	return nil
}

type GetBioResponse struct {
	Bio                  *Bio     `protobuf:"bytes,1,opt,name=bio,proto3" json:"bio,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBioResponse) Reset()         { *m = GetBioResponse{} }
func (m *GetBioResponse) String() string { return proto.CompactTextString(m) }
func (*GetBioResponse) ProtoMessage()    {}
func (*GetBioResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7973498bfb7f266, []int{15}
}
func (m *GetBioResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBioResponse.Unmarshal(m, b)
}
func (m *GetBioResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBioResponse.Marshal(b, m, deterministic)
}
func (m *GetBioResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBioResponse.Merge(m, src)
}
func (m *GetBioResponse) XXX_Size() int {
	return xxx_messageInfo_GetBioResponse.Size(m)
}
func (m *GetBioResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBioResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBioResponse proto.InternalMessageInfo

func (m *GetBioResponse) GetBio() *Bio {
	if m != nil {
		return m.Bio
	}
	return nil
}

type GetBioRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBioRequest) Reset()         { *m = GetBioRequest{} }
func (m *GetBioRequest) String() string { return proto.CompactTextString(m) }
func (*GetBioRequest) ProtoMessage()    {}
func (*GetBioRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7973498bfb7f266, []int{16}
}
func (m *GetBioRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBioRequest.Unmarshal(m, b)
}
func (m *GetBioRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBioRequest.Marshal(b, m, deterministic)
}
func (m *GetBioRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBioRequest.Merge(m, src)
}
func (m *GetBioRequest) XXX_Size() int {
	return xxx_messageInfo_GetBioRequest.Size(m)
}
func (m *GetBioRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBioRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBioRequest proto.InternalMessageInfo

type GetCVResponse struct {
	Skills               *Skills     `protobuf:"bytes,1,opt,name=skills,proto3" json:"skills,omitempty"`
	Jobs                 *Experience `protobuf:"bytes,2,opt,name=jobs,proto3" json:"jobs,omitempty"`
	Courses              *Education  `protobuf:"bytes,3,opt,name=courses,proto3" json:"courses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetCVResponse) Reset()         { *m = GetCVResponse{} }
func (m *GetCVResponse) String() string { return proto.CompactTextString(m) }
func (*GetCVResponse) ProtoMessage()    {}
func (*GetCVResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7973498bfb7f266, []int{17}
}
func (m *GetCVResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCVResponse.Unmarshal(m, b)
}
func (m *GetCVResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCVResponse.Marshal(b, m, deterministic)
}
func (m *GetCVResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCVResponse.Merge(m, src)
}
func (m *GetCVResponse) XXX_Size() int {
	return xxx_messageInfo_GetCVResponse.Size(m)
}
func (m *GetCVResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCVResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCVResponse proto.InternalMessageInfo

func (m *GetCVResponse) GetSkills() *Skills {
	if m != nil {
		return m.Skills
	}
	return nil
}

func (m *GetCVResponse) GetJobs() *Experience {
	if m != nil {
		return m.Jobs
	}
	return nil
}

func (m *GetCVResponse) GetCourses() *Education {
	if m != nil {
		return m.Courses
	}
	return nil
}

type GetCVRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCVRequest) Reset()         { *m = GetCVRequest{} }
func (m *GetCVRequest) String() string { return proto.CompactTextString(m) }
func (*GetCVRequest) ProtoMessage()    {}
func (*GetCVRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7973498bfb7f266, []int{18}
}
func (m *GetCVRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCVRequest.Unmarshal(m, b)
}
func (m *GetCVRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCVRequest.Marshal(b, m, deterministic)
}
func (m *GetCVRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCVRequest.Merge(m, src)
}
func (m *GetCVRequest) XXX_Size() int {
	return xxx_messageInfo_GetCVRequest.Size(m)
}
func (m *GetCVRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCVRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCVRequest proto.InternalMessageInfo

type ListProjectsResponse struct {
	Projects             *Projects `protobuf:"bytes,1,opt,name=projects,proto3" json:"projects,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ListProjectsResponse) Reset()         { *m = ListProjectsResponse{} }
func (m *ListProjectsResponse) String() string { return proto.CompactTextString(m) }
func (*ListProjectsResponse) ProtoMessage()    {}
func (*ListProjectsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7973498bfb7f266, []int{19}
}
func (m *ListProjectsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListProjectsResponse.Unmarshal(m, b)
}
func (m *ListProjectsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListProjectsResponse.Marshal(b, m, deterministic)
}
func (m *ListProjectsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListProjectsResponse.Merge(m, src)
}
func (m *ListProjectsResponse) XXX_Size() int {
	return xxx_messageInfo_ListProjectsResponse.Size(m)
}
func (m *ListProjectsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListProjectsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListProjectsResponse proto.InternalMessageInfo

func (m *ListProjectsResponse) GetProjects() *Projects {
	if m != nil {
		return m.Projects
	}
	return nil
}

type ListProjectsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListProjectsRequest) Reset()         { *m = ListProjectsRequest{} }
func (m *ListProjectsRequest) String() string { return proto.CompactTextString(m) }
func (*ListProjectsRequest) ProtoMessage()    {}
func (*ListProjectsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7973498bfb7f266, []int{20}
}
func (m *ListProjectsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListProjectsRequest.Unmarshal(m, b)
}
func (m *ListProjectsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListProjectsRequest.Marshal(b, m, deterministic)
}
func (m *ListProjectsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListProjectsRequest.Merge(m, src)
}
func (m *ListProjectsRequest) XXX_Size() int {
	return xxx_messageInfo_ListProjectsRequest.Size(m)
}
func (m *ListProjectsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListProjectsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListProjectsRequest proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Bio)(nil), "proto.Bio")
	proto.RegisterType((*Course)(nil), "proto.Course")
	proto.RegisterType((*Education)(nil), "proto.Education")
	proto.RegisterType((*Skill)(nil), "proto.Skill")
	proto.RegisterType((*Skills)(nil), "proto.Skills")
	proto.RegisterType((*Project)(nil), "proto.Project")
	proto.RegisterType((*Projects)(nil), "proto.Projects")
	proto.RegisterType((*Job)(nil), "proto.Job")
	proto.RegisterType((*Experience)(nil), "proto.Experience")
	proto.RegisterType((*AddBioResponse)(nil), "proto.AddBioResponse")
	proto.RegisterType((*AddBioRequest)(nil), "proto.AddBioRequest")
	proto.RegisterType((*AddCVResponse)(nil), "proto.AddCVResponse")
	proto.RegisterType((*AddCVRequest)(nil), "proto.AddCVRequest")
	proto.RegisterType((*AddProjectsResponse)(nil), "proto.AddProjectsResponse")
	proto.RegisterType((*AddProjectsRequest)(nil), "proto.AddProjectsRequest")
	proto.RegisterType((*GetBioResponse)(nil), "proto.GetBioResponse")
	proto.RegisterType((*GetBioRequest)(nil), "proto.GetBioRequest")
	proto.RegisterType((*GetCVResponse)(nil), "proto.GetCVResponse")
	proto.RegisterType((*GetCVRequest)(nil), "proto.GetCVRequest")
	proto.RegisterType((*ListProjectsResponse)(nil), "proto.ListProjectsResponse")
	proto.RegisterType((*ListProjectsRequest)(nil), "proto.ListProjectsRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PortfolioServiceClient is the client API for PortfolioService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PortfolioServiceClient interface {
	AddBio(ctx context.Context, in *AddBioRequest, opts ...grpc.CallOption) (PortfolioService_AddBioClient, error)
	AddCV(ctx context.Context, in *AddCVRequest, opts ...grpc.CallOption) (PortfolioService_AddCVClient, error)
	AddProjects(ctx context.Context, in *AddProjectsRequest, opts ...grpc.CallOption) (PortfolioService_AddProjectsClient, error)
	GetBio(ctx context.Context, in *GetBioRequest, opts ...grpc.CallOption) (PortfolioService_GetBioClient, error)
	GetCV(ctx context.Context, in *GetCVRequest, opts ...grpc.CallOption) (PortfolioService_GetCVClient, error)
	ListProjects(ctx context.Context, in *ListProjectsRequest, opts ...grpc.CallOption) (PortfolioService_ListProjectsClient, error)
}

type portfolioServiceClient struct {
	cc *grpc.ClientConn
}

func NewPortfolioServiceClient(cc *grpc.ClientConn) PortfolioServiceClient {
	return &portfolioServiceClient{cc}
}

func (c *portfolioServiceClient) AddBio(ctx context.Context, in *AddBioRequest, opts ...grpc.CallOption) (PortfolioService_AddBioClient, error) {
	stream, err := c.cc.NewStream(ctx, &_PortfolioService_serviceDesc.Streams[0], "/proto.PortfolioService/AddBio", opts...)
	if err != nil {
		return nil, err
	}
	x := &portfolioServiceAddBioClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PortfolioService_AddBioClient interface {
	Recv() (*AddBioResponse, error)
	grpc.ClientStream
}

type portfolioServiceAddBioClient struct {
	grpc.ClientStream
}

func (x *portfolioServiceAddBioClient) Recv() (*AddBioResponse, error) {
	m := new(AddBioResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *portfolioServiceClient) AddCV(ctx context.Context, in *AddCVRequest, opts ...grpc.CallOption) (PortfolioService_AddCVClient, error) {
	stream, err := c.cc.NewStream(ctx, &_PortfolioService_serviceDesc.Streams[1], "/proto.PortfolioService/AddCV", opts...)
	if err != nil {
		return nil, err
	}
	x := &portfolioServiceAddCVClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PortfolioService_AddCVClient interface {
	Recv() (*AddCVResponse, error)
	grpc.ClientStream
}

type portfolioServiceAddCVClient struct {
	grpc.ClientStream
}

func (x *portfolioServiceAddCVClient) Recv() (*AddCVResponse, error) {
	m := new(AddCVResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *portfolioServiceClient) AddProjects(ctx context.Context, in *AddProjectsRequest, opts ...grpc.CallOption) (PortfolioService_AddProjectsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_PortfolioService_serviceDesc.Streams[2], "/proto.PortfolioService/AddProjects", opts...)
	if err != nil {
		return nil, err
	}
	x := &portfolioServiceAddProjectsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PortfolioService_AddProjectsClient interface {
	Recv() (*AddProjectsResponse, error)
	grpc.ClientStream
}

type portfolioServiceAddProjectsClient struct {
	grpc.ClientStream
}

func (x *portfolioServiceAddProjectsClient) Recv() (*AddProjectsResponse, error) {
	m := new(AddProjectsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *portfolioServiceClient) GetBio(ctx context.Context, in *GetBioRequest, opts ...grpc.CallOption) (PortfolioService_GetBioClient, error) {
	stream, err := c.cc.NewStream(ctx, &_PortfolioService_serviceDesc.Streams[3], "/proto.PortfolioService/GetBio", opts...)
	if err != nil {
		return nil, err
	}
	x := &portfolioServiceGetBioClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PortfolioService_GetBioClient interface {
	Recv() (*GetBioResponse, error)
	grpc.ClientStream
}

type portfolioServiceGetBioClient struct {
	grpc.ClientStream
}

func (x *portfolioServiceGetBioClient) Recv() (*GetBioResponse, error) {
	m := new(GetBioResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *portfolioServiceClient) GetCV(ctx context.Context, in *GetCVRequest, opts ...grpc.CallOption) (PortfolioService_GetCVClient, error) {
	stream, err := c.cc.NewStream(ctx, &_PortfolioService_serviceDesc.Streams[4], "/proto.PortfolioService/GetCV", opts...)
	if err != nil {
		return nil, err
	}
	x := &portfolioServiceGetCVClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PortfolioService_GetCVClient interface {
	Recv() (*GetCVResponse, error)
	grpc.ClientStream
}

type portfolioServiceGetCVClient struct {
	grpc.ClientStream
}

func (x *portfolioServiceGetCVClient) Recv() (*GetCVResponse, error) {
	m := new(GetCVResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *portfolioServiceClient) ListProjects(ctx context.Context, in *ListProjectsRequest, opts ...grpc.CallOption) (PortfolioService_ListProjectsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_PortfolioService_serviceDesc.Streams[5], "/proto.PortfolioService/ListProjects", opts...)
	if err != nil {
		return nil, err
	}
	x := &portfolioServiceListProjectsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PortfolioService_ListProjectsClient interface {
	Recv() (*ListProjectsResponse, error)
	grpc.ClientStream
}

type portfolioServiceListProjectsClient struct {
	grpc.ClientStream
}

func (x *portfolioServiceListProjectsClient) Recv() (*ListProjectsResponse, error) {
	m := new(ListProjectsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PortfolioServiceServer is the server API for PortfolioService service.
type PortfolioServiceServer interface {
	AddBio(*AddBioRequest, PortfolioService_AddBioServer) error
	AddCV(*AddCVRequest, PortfolioService_AddCVServer) error
	AddProjects(*AddProjectsRequest, PortfolioService_AddProjectsServer) error
	GetBio(*GetBioRequest, PortfolioService_GetBioServer) error
	GetCV(*GetCVRequest, PortfolioService_GetCVServer) error
	ListProjects(*ListProjectsRequest, PortfolioService_ListProjectsServer) error
}

func RegisterPortfolioServiceServer(s *grpc.Server, srv PortfolioServiceServer) {
	s.RegisterService(&_PortfolioService_serviceDesc, srv)
}

func _PortfolioService_AddBio_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(AddBioRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PortfolioServiceServer).AddBio(m, &portfolioServiceAddBioServer{stream})
}

type PortfolioService_AddBioServer interface {
	Send(*AddBioResponse) error
	grpc.ServerStream
}

type portfolioServiceAddBioServer struct {
	grpc.ServerStream
}

func (x *portfolioServiceAddBioServer) Send(m *AddBioResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _PortfolioService_AddCV_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(AddCVRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PortfolioServiceServer).AddCV(m, &portfolioServiceAddCVServer{stream})
}

type PortfolioService_AddCVServer interface {
	Send(*AddCVResponse) error
	grpc.ServerStream
}

type portfolioServiceAddCVServer struct {
	grpc.ServerStream
}

func (x *portfolioServiceAddCVServer) Send(m *AddCVResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _PortfolioService_AddProjects_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(AddProjectsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PortfolioServiceServer).AddProjects(m, &portfolioServiceAddProjectsServer{stream})
}

type PortfolioService_AddProjectsServer interface {
	Send(*AddProjectsResponse) error
	grpc.ServerStream
}

type portfolioServiceAddProjectsServer struct {
	grpc.ServerStream
}

func (x *portfolioServiceAddProjectsServer) Send(m *AddProjectsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _PortfolioService_GetBio_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetBioRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PortfolioServiceServer).GetBio(m, &portfolioServiceGetBioServer{stream})
}

type PortfolioService_GetBioServer interface {
	Send(*GetBioResponse) error
	grpc.ServerStream
}

type portfolioServiceGetBioServer struct {
	grpc.ServerStream
}

func (x *portfolioServiceGetBioServer) Send(m *GetBioResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _PortfolioService_GetCV_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetCVRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PortfolioServiceServer).GetCV(m, &portfolioServiceGetCVServer{stream})
}

type PortfolioService_GetCVServer interface {
	Send(*GetCVResponse) error
	grpc.ServerStream
}

type portfolioServiceGetCVServer struct {
	grpc.ServerStream
}

func (x *portfolioServiceGetCVServer) Send(m *GetCVResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _PortfolioService_ListProjects_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListProjectsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PortfolioServiceServer).ListProjects(m, &portfolioServiceListProjectsServer{stream})
}

type PortfolioService_ListProjectsServer interface {
	Send(*ListProjectsResponse) error
	grpc.ServerStream
}

type portfolioServiceListProjectsServer struct {
	grpc.ServerStream
}

func (x *portfolioServiceListProjectsServer) Send(m *ListProjectsResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _PortfolioService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.PortfolioService",
	HandlerType: (*PortfolioServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AddBio",
			Handler:       _PortfolioService_AddBio_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "AddCV",
			Handler:       _PortfolioService_AddCV_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "AddProjects",
			Handler:       _PortfolioService_AddProjects_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetBio",
			Handler:       _PortfolioService_GetBio_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetCV",
			Handler:       _PortfolioService_GetCV_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ListProjects",
			Handler:       _PortfolioService_ListProjects_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/portfolio.proto",
}

func init() { proto.RegisterFile("proto/portfolio.proto", fileDescriptor_d7973498bfb7f266) }

var fileDescriptor_d7973498bfb7f266 = []byte{
	// 674 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x94, 0x4d, 0x6f, 0xd3, 0x30,
	0x18, 0xc7, 0x95, 0xa6, 0xcd, 0xba, 0x67, 0x6d, 0x37, 0xbc, 0x16, 0x65, 0x19, 0x42, 0x53, 0xc4,
	0xc4, 0x34, 0xa0, 0xa0, 0x31, 0xb1, 0x13, 0x87, 0xbd, 0x81, 0x36, 0x71, 0x98, 0x32, 0xe0, 0x3a,
	0x35, 0x8d, 0x99, 0x5c, 0xb2, 0x38, 0xc4, 0x2e, 0x82, 0x33, 0x12, 0x82, 0xcf, 0xc4, 0x97, 0x43,
	0x79, 0x6c, 0xe7, 0xa5, 0x99, 0x04, 0x9c, 0x38, 0x2d, 0x7e, 0xde, 0xfc, 0x7b, 0xfe, 0xfe, 0xaf,
	0x30, 0x4a, 0x33, 0x2e, 0xf9, 0xd3, 0x94, 0x67, 0xf2, 0x03, 0x8f, 0x19, 0x1f, 0xe3, 0x99, 0x74,
	0xf0, 0x8f, 0xff, 0x12, 0xec, 0x23, 0xc6, 0xc9, 0x10, 0x3a, 0x92, 0xc9, 0x98, 0xba, 0xd6, 0x96,
	0xb5, 0xb3, 0x1c, 0xa8, 0x03, 0xd9, 0x82, 0x95, 0x88, 0x8a, 0x69, 0xc6, 0x52, 0xc9, 0x78, 0xe2,
	0xb6, 0x30, 0x57, 0x0d, 0xf9, 0xdf, 0x2d, 0x70, 0x8e, 0xf9, 0x3c, 0x13, 0x94, 0x0c, 0xa0, 0x75,
	0x76, 0x82, 0xfd, 0xfd, 0xa0, 0xc5, 0x4e, 0xf2, 0x66, 0x96, 0x08, 0xc9, 0xe4, 0xbc, 0xda, 0x5c,
	0x09, 0x2d, 0x8e, 0xb7, 0x1b, 0xe3, 0x73, 0xac, 0x68, 0x22, 0xa9, 0x70, 0xdb, 0x0a, 0x0b, 0x0f,
	0x84, 0x40, 0x3b, 0x99, 0xdc, 0x50, 0xb7, 0x83, 0x41, 0xfc, 0xf6, 0xf7, 0x61, 0xf9, 0x34, 0x9a,
	0x4f, 0x27, 0xd8, 0xf6, 0x10, 0x96, 0xa6, 0x08, 0x25, 0x5c, 0x6b, 0xcb, 0xde, 0x59, 0xd9, 0xeb,
	0xab, 0xa5, 0xc7, 0x0a, 0x35, 0x30, 0x59, 0x9f, 0x42, 0xe7, 0xf2, 0x23, 0x8b, 0xe3, 0x06, 0xbc,
	0xb9, 0xa2, 0x55, 0x5e, 0x41, 0xee, 0x82, 0x93, 0x4d, 0x24, 0x4b, 0xae, 0x91, 0xb4, 0x1f, 0xe8,
	0xd3, 0xe2, 0x1a, 0xed, 0xa6, 0x4a, 0x63, 0x70, 0xf0, 0x1a, 0x41, 0x1e, 0x80, 0x23, 0xf0, 0x4b,
	0x83, 0xf5, 0x34, 0x18, 0xa6, 0x03, 0x9d, 0xf3, 0x29, 0x2c, 0x5d, 0x64, 0x7c, 0x46, 0xa7, 0xb2,
	0x01, 0x56, 0x3c, 0x54, 0xab, 0xfa, 0x50, 0x04, 0xda, 0x37, 0x54, 0x4e, 0xb4, 0x84, 0xf8, 0xfd,
	0x17, 0x58, 0x2f, 0xa0, 0xab, 0xaf, 0x11, 0x64, 0x17, 0xba, 0xa9, 0xfe, 0xd6, 0x68, 0x03, 0x8d,
	0xa6, 0x4b, 0x82, 0x22, 0xef, 0xff, 0xb2, 0xc0, 0x3e, 0xe7, 0x61, 0x83, 0xcd, 0xcd, 0x65, 0xbf,
	0x49, 0x27, 0xc9, 0x57, 0x4d, 0x67, 0x8e, 0x64, 0x13, 0x96, 0x67, 0x3c, 0xbc, 0x52, 0xe4, 0x0a,
	0xb2, 0x3b, 0xe3, 0xe1, 0x5b, 0x84, 0xf7, 0xa0, 0x1b, 0x73, 0xf5, 0x72, 0x9a, 0xb2, 0x38, 0x97,
	0x06, 0xe8, 0x54, 0x0d, 0xb0, 0xb0, 0x9a, 0xd3, 0x34, 0xce, 0x46, 0x3e, 0xf3, 0x9a, 0x5f, 0xcd,
	0xb3, 0xd8, 0x5d, 0x52, 0x2c, 0xf9, 0xf9, 0x5d, 0x16, 0xfb, 0x8f, 0x01, 0x4e, 0xbf, 0xa4, 0x34,
	0x63, 0x34, 0x99, 0x52, 0x72, 0x1f, 0xda, 0x33, 0x1e, 0x9a, 0x9d, 0x41, 0xef, 0x7c, 0xce, 0xc3,
	0x00, 0xe3, 0xfe, 0x1a, 0x0c, 0x0e, 0xa3, 0xe8, 0x88, 0xf1, 0x80, 0x8a, 0x94, 0x27, 0x82, 0xfa,
	0x4f, 0xa0, 0x6f, 0x22, 0x9f, 0xe6, 0x54, 0x48, 0x72, 0x0f, 0xec, 0x90, 0x71, 0xd4, 0xa1, 0x9c,
	0x90, 0xe7, 0xf3, 0xb0, 0xbf, 0x8a, 0xe5, 0xc7, 0xef, 0x8b, 0xfe, 0x1f, 0x16, 0xf4, 0x74, 0x44,
	0xf5, 0x6f, 0x57, 0x3c, 0x61, 0x55, 0xcc, 0xaa, 0x2c, 0x63, 0x4c, 0x41, 0xb6, 0x35, 0x69, 0x0b,
	0x8b, 0xee, 0xe8, 0xa2, 0x72, 0x15, 0x05, 0x4c, 0x76, 0x4b, 0xef, 0xdb, 0x58, 0xb9, 0x66, 0x2a,
	0xcd, 0xbf, 0x47, 0x69, 0xff, 0x11, 0xac, 0x1f, 0x46, 0x91, 0xf1, 0x40, 0x41, 0x78, 0x08, 0xa4,
	0x16, 0x56, 0x98, 0x8f, 0x6a, 0x0e, 0xc9, 0x27, 0xaf, 0xd6, 0x1d, 0x22, 0x2a, 0x16, 0x19, 0xc3,
	0xe0, 0x35, 0x95, 0x15, 0xd9, 0xfe, 0xac, 0x92, 0xa9, 0xc7, 0xdb, 0xfc, 0x9f, 0x16, 0x46, 0x4a,
	0xdd, 0xfe, 0xa3, 0x4c, 0x03, 0xe8, 0x69, 0x14, 0xc5, 0x76, 0x0c, 0xc3, 0x37, 0x4c, 0xc8, 0x45,
	0xdd, 0xfe, 0x4d, 0xa1, 0x11, 0xac, 0xd7, 0x87, 0xe0, 0xec, 0xbd, 0x6f, 0x36, 0xac, 0x5d, 0x98,
	0x9f, 0xea, 0x4b, 0x9a, 0x7d, 0x66, 0x53, 0x4a, 0x0e, 0xc0, 0x51, 0x96, 0x23, 0x43, 0x3d, 0xb0,
	0xe6, 0x40, 0x6f, 0xb4, 0x10, 0x55, 0x3c, 0xcf, 0x2c, 0xb2, 0x0f, 0x1d, 0xb4, 0x1a, 0x59, 0x2f,
	0x2b, 0x8a, 0x3d, 0xbc, 0x61, 0x3d, 0x58, 0x74, 0xbd, 0x82, 0x95, 0xca, 0xfb, 0x93, 0x8d, 0xb2,
	0x6c, 0x81, 0xd6, 0xf3, 0x6e, 0x4b, 0x15, 0x73, 0x0e, 0xc0, 0x51, 0x8f, 0x5a, 0x60, 0xd7, 0xde,
	0xb8, 0xc0, 0xae, 0x3b, 0x45, 0x61, 0xa3, 0xe0, 0x05, 0x76, 0x55, 0x7e, 0x6f, 0x58, 0x0f, 0x16,
	0x5d, 0x67, 0xd0, 0xab, 0x2a, 0x4a, 0x0c, 0xdc, 0x2d, 0x32, 0x7b, 0x9b, 0xb7, 0xe6, 0xcc, 0xa8,
	0xd0, 0xc1, 0xec, 0xf3, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xe1, 0xf0, 0x60, 0x11, 0x3c, 0x07,
	0x00, 0x00,
}
